/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ar.com.ventas.frame;

import ar.com.ventas.entities.Administrador;
import ar.com.ventas.entities.Consorcio;
import ar.com.ventas.entities.CuentaCorrienteCliente;
import ar.com.ventas.services.AdministradorService;
import ar.com.ventas.services.ConsorcioService;
import ar.com.ventas.services.CuentaCorrienteClienteService;
import java.util.ArrayList;
import java.util.Date;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author Mario
 */
public class A1Tst_cuentaCorrienteFrame extends javax.swing.JFrame {

    /**
     * Creates new form A1Tst_cuentaCorrienteFrame
     */
    public A1Tst_cuentaCorrienteFrame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        goBtn = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        goBtn.setText("go");
        goBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                goBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(345, Short.MAX_VALUE)
                .addComponent(goBtn)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(266, Short.MAX_VALUE)
                .addComponent(goBtn)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void goBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_goBtnActionPerformed
        go();
    }//GEN-LAST:event_goBtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(A1Tst_cuentaCorrienteFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(A1Tst_cuentaCorrienteFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(A1Tst_cuentaCorrienteFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(A1Tst_cuentaCorrienteFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new A1Tst_cuentaCorrienteFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton goBtn;
    // End of variables declaration//GEN-END:variables

    private void go() {
        Administrador adm = null;
        Date de = new Date();
        Date al = new Date();
        try {
            adm = new AdministradorService().getAdministradorById(10L);
        } catch (Exception ex) {
            Logger.getLogger(A1Tst_cuentaCorrienteFrame.class.getName()).log(Level.SEVERE, null, ex);
        }
        List<Consorcio> cons = null;
        try {
            cons = new ConsorcioService().getAllConsorciosActivosByAdministrador(adm);
        } catch (Exception ex) {
            Logger.getLogger(A1Tst_cuentaCorrienteFrame.class.getName()).log(Level.SEVERE, null, ex);
        }
        List<CuentaCorrienteCliente> ctaCte = null;
        List<CuentaCorrienteCliente> cuentaCte = new ArrayList<>();
        for (Consorcio co : cons) {
//            System.out.println(co.getCodigo());
            try {
                ctaCte = new CuentaCorrienteClienteService()
                        .getCtaCteDeVariosClientesEntreFechas(co, de, al);
            } catch (Exception ex) {
                Logger.getLogger(A1Tst_cuentaCorrienteFrame.class.getName()).log(Level.SEVERE, null, ex);
            }
            if (ctaCte != null && !ctaCte.isEmpty()) {
                for (CuentaCorrienteCliente cc : ctaCte) {
//                    System.out.println(cc.getFecha());
                    cuentaCte.add(cc);
                }
            }
        }
        for (CuentaCorrienteCliente ccc : cuentaCte) {
            System.out.println(ccc.getSaldo());
            System.out.println(ccc.getFecha());
        }
    }
}
