/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ar.com.ventas.frame;

import ar.com.ventas.entities.Consorcio;
import ar.com.ventas.entities.Domicilio;
import ar.com.ventas.entities.Estructura;
import ar.com.ventas.entities.EstructuraServicio;
import ar.com.ventas.entities.Persona;
import ar.com.ventas.entities.RenglonTrabajo;
import ar.com.ventas.entities.Rubro;
import ar.com.ventas.entities.Trabajo;
import ar.com.ventas.entities.Servicio;
import ar.com.ventas.estructuras.CampoEstructura;
import ar.com.ventas.estructuras.Constantes;
import ar.com.ventas.main.MainFrame;
import ar.com.ventas.services.EstructuraServicioService;
import ar.com.ventas.services.PersonaService;
import ar.com.ventas.services.TrabajoService;
import ar.com.ventas.util.UtilFrame;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Date;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Mario
 */
public class ActualizarTrabajoFrame extends javax.swing.JFrame {

    private final SimpleDateFormat sdf = new SimpleDateFormat("dd/MM/yyyy");
    private List<RenglonTrabajo> renglones = null;
    private List<Persona> personas;
    private List<EstructuraServicio> es = null;
    private final Trabajo trabajo;
    private Date fechaCargar;

    /**
     * Creates new form NuevoServicioFrame
     *
     * @param trabajo
     * @param renglones
     */
    public ActualizarTrabajoFrame(Trabajo trabajo, List<RenglonTrabajo> renglones) {
        initComponents();
        getContentPane().setBackground(new java.awt.Color(Constantes.getR(), Constantes.getG(), Constantes.getB()));
        this.setLocationRelativeTo(null);
//        setExtendedState(this.MAXIMIZED_BOTH);
        this.trabajo = trabajo;
        this.renglones = renglones;
        llenarListas();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        volverBtn = new javax.swing.JButton();
        guardarBtn = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        tabla = new javax.swing.JTable();
        completarBtn = new javax.swing.JButton();
        personaLbl = new javax.swing.JLabel();
        comboP = new javax.swing.JComboBox<>();
        fechaLbl = new javax.swing.JLabel();
        fecha2Txt = new javax.swing.JTextField();
        textoLbl = new javax.swing.JLabel();
        textoTxt = new javax.swing.JTextField();
        cantidadLbl = new javax.swing.JLabel();
        cantidadTxt = new javax.swing.JTextField();
        importeLbl = new javax.swing.JLabel();
        importeTxt = new javax.swing.JTextField();
        opcionLbl = new javax.swing.JLabel();
        comboO = new javax.swing.JComboBox<>();
        cargarBtn = new javax.swing.JButton();
        descartarBtn = new javax.swing.JButton();
        consorcioTxt = new javax.swing.JTextField();
        servicioTxt = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setTitle("ACTUALIZAR TRABAJO");

        jLabel1.setText("Consorcio:");

        jLabel2.setText("Servicio:");

        volverBtn.setText("Volver");
        volverBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                volverBtnActionPerformed(evt);
            }
        });

        guardarBtn.setText("Guardar");
        guardarBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                guardarBtnActionPerformed(evt);
            }
        });

        tabla.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "CAMPO", "CONTENIDO"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tabla.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tablaMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(tabla);

        completarBtn.setText("Completar");
        completarBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                completarBtnActionPerformed(evt);
            }
        });

        personaLbl.setText("Persona:");

        comboP.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        comboP.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                comboPMouseClicked(evt);
            }
        });
        comboP.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                comboPKeyPressed(evt);
            }
        });

        fechaLbl.setText("Fecha:");

        fecha2Txt.setText("FECHA");
        fecha2Txt.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                fecha2TxtKeyPressed(evt);
            }
        });

        textoLbl.setText("Texto:");

        textoTxt.setText("TEXTO");
        textoTxt.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                textoTxtKeyPressed(evt);
            }
        });

        cantidadLbl.setText("Cantidad:");

        cantidadTxt.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        cantidadTxt.setText("CATIDAD");
        cantidadTxt.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                cantidadTxtKeyPressed(evt);
            }
        });

        importeLbl.setText("Importe:");

        importeTxt.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        importeTxt.setText("IMPORTE");
        importeTxt.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                importeTxtKeyPressed(evt);
            }
        });

        opcionLbl.setText("Opción:");

        comboO.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { " ", "SI", "NO" }));
        comboO.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                comboOMouseClicked(evt);
            }
        });
        comboO.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                comboOKeyPressed(evt);
            }
        });

        cargarBtn.setText("Cargar");
        cargarBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cargarBtnActionPerformed(evt);
            }
        });

        descartarBtn.setText("Descartar");
        descartarBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                descartarBtnActionPerformed(evt);
            }
        });

        consorcioTxt.setText("CONSORCIO");

        servicioTxt.setText("SERVICIO");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(guardarBtn)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(volverBtn))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 671, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(93, 93, 93)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(textoLbl)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(textoTxt))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(cantidadLbl)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(cantidadTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(personaLbl)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(comboP, javax.swing.GroupLayout.PREFERRED_SIZE, 347, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(fechaLbl)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(fecha2Txt, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(opcionLbl)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(comboO, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addGroup(layout.createSequentialGroup()
                                            .addComponent(cargarBtn)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(descartarBtn))
                                        .addGroup(layout.createSequentialGroup()
                                            .addComponent(importeLbl)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                            .addComponent(importeTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                .addGap(0, 69, Short.MAX_VALUE))))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(completarBtn)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel1)
                                    .addComponent(jLabel2))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(consorcioTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 648, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addGap(10, 10, 10)
                                        .addComponent(servicioTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 648, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(consorcioTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(personaLbl)
                    .addComponent(comboP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(servicioTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(fechaLbl)
                    .addComponent(fecha2Txt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(textoLbl)
                            .addComponent(textoTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(cantidadLbl)
                            .addComponent(cantidadTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(importeLbl)
                            .addComponent(importeTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(opcionLbl)
                            .addComponent(comboO, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(cargarBtn)
                            .addComponent(descartarBtn))
                        .addGap(167, 167, 167))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 332, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                .addComponent(completarBtn)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(volverBtn)
                    .addComponent(guardarBtn))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void volverBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_volverBtnActionPerformed
        volver();
    }//GEN-LAST:event_volverBtnActionPerformed

    private void guardarBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_guardarBtnActionPerformed
        guardar();
    }//GEN-LAST:event_guardarBtnActionPerformed

    private void completarBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_completarBtnActionPerformed
        completar();
    }//GEN-LAST:event_completarBtnActionPerformed

    private void descartarBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_descartarBtnActionPerformed
        descartar();
    }//GEN-LAST:event_descartarBtnActionPerformed

    private void cargarBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cargarBtnActionPerformed
        cargar();
    }//GEN-LAST:event_cargarBtnActionPerformed

    private void tablaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tablaMouseClicked
        ocultarCampos();
        completar();
    }//GEN-LAST:event_tablaMouseClicked

    private void fecha2TxtKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_fecha2TxtKeyPressed
        if (evt.getKeyCode() == 10) {
            String fe = fecha2Txt.getText();

            int largo = fe.length();
            if (largo == 10) {
                Date f = new Date();
                try {
                    f = sdf.parse(fe);
                } catch (ParseException ex) {
                    Logger.getLogger(ActualizarTrabajoFrame.class.getName()).log(Level.SEVERE, null, ex);
                    JOptionPane.showMessageDialog(this, "ERROR EN FECHA");
                    fecha2Txt.requestFocus();
                    return;
                }
                fechaCargar = f;
                trabajo.setFecha(f);
                cargar();
            } else {
                fe = UtilFrame.fecha(fe);
                fecha2Txt.setText(fe);
            }
        }
    }//GEN-LAST:event_fecha2TxtKeyPressed

    private void textoTxtKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_textoTxtKeyPressed
        if (evt.getKeyCode() == 10) {
            cargar();
        }
    }//GEN-LAST:event_textoTxtKeyPressed

    private void comboPKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_comboPKeyPressed
        int row = comboP.getSelectedIndex();
        if (row > 0) {
            if (evt.getKeyCode() == 10) {
                cargar();
            }
        }
    }//GEN-LAST:event_comboPKeyPressed

    private void cantidadTxtKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_cantidadTxtKeyPressed
        if (evt.getKeyCode() == 10) {
            cargar();
        }
    }//GEN-LAST:event_cantidadTxtKeyPressed

    private void importeTxtKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_importeTxtKeyPressed
        if (evt.getKeyCode() == 10) {
            cargar();
        }
    }//GEN-LAST:event_importeTxtKeyPressed

    private void comboOKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_comboOKeyPressed
        int row = comboO.getSelectedIndex();
        if (row > 0) {
            if (evt.getKeyCode() == 10) {
                cargar();
            }
        }
    }//GEN-LAST:event_comboOKeyPressed

    private void comboOMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_comboOMouseClicked
        int row = comboO.getSelectedIndex();
        if (row > 0) {
            if (evt.getModifiers() == 16) {
                cargar();
            }
        }
    }//GEN-LAST:event_comboOMouseClicked

    private void comboPMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_comboPMouseClicked
        int row = comboP.getSelectedIndex();
        if (row > 0) {
            if (evt.getModifiers() == 16) {
                cargar();
            }
        }
    }//GEN-LAST:event_comboPMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ActualizarTrabajoFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ActualizarTrabajoFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ActualizarTrabajoFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ActualizarTrabajoFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ActualizarTrabajoFrame(null, null).setVisible(true);
            }
        });
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel cantidadLbl;
    private javax.swing.JTextField cantidadTxt;
    private javax.swing.JButton cargarBtn;
    private javax.swing.JComboBox<String> comboO;
    private javax.swing.JComboBox<String> comboP;
    private javax.swing.JButton completarBtn;
    private javax.swing.JTextField consorcioTxt;
    private javax.swing.JButton descartarBtn;
    private javax.swing.JTextField fecha2Txt;
    private javax.swing.JLabel fechaLbl;
    private javax.swing.JButton guardarBtn;
    private javax.swing.JLabel importeLbl;
    private javax.swing.JTextField importeTxt;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel opcionLbl;
    private javax.swing.JLabel personaLbl;
    private javax.swing.JTextField servicioTxt;
    private javax.swing.JTable tabla;
    private javax.swing.JLabel textoLbl;
    private javax.swing.JTextField textoTxt;
    private javax.swing.JButton volverBtn;
    // End of variables declaration//GEN-END:variables

    private void llenarListas() {
        tabla.requestFocus();
        consorcioTxt.setEditable(false);
        servicioTxt.setEditable(false);
        limpiarCampos();
        Servicio servicio = trabajo.getServicio();
        Consorcio consorcio = servicio.getConsorcio();
        Domicilio dom = consorcio.getDomicilio();
        String conso = dom.getCalle() + " " + dom.getNumero();
        consorcioTxt.setText(conso);
        servicioTxt.setText(servicio.getRubro().getDetalle());
        fechaCargar = trabajo.getFecha();
        cargarRenglones();
    }

    private void guardar() {
        if (validar()) {
//            Date f = new Date();
//            Servicio servicio = trabajo.getServicio();
            // Trabajo trabajo = new Trabajo();
//            trabajo.setActivo(true);
//            trabajo.setCuota(1);
//            trabajo.setFacturaEmitida(false);
//            trabajo.setReciboEmitido(false);
            trabajo.setFecha(fechaCargar);
//            trabajo.setTextoEnFactura("");
//            trabajo.setServicio(servicio);
            for (RenglonTrabajo rs : renglones) {
                rs.setTrabajo(trabajo);
            }
            try {
                new TrabajoService().updateTrabajoCompleto(trabajo, renglones);
                JOptionPane.showMessageDialog(this, "TRABAJO GUARDADO CORRECTAMENTE");
            } catch (Exception ex) {
                Logger.getLogger(ActualizarTrabajoFrame.class.getName()).log(Level.SEVERE, null, ex);
                JOptionPane.showMessageDialog(this, "ERROR Nro. 569 GUARDANDO TRABAJO");
                return;
            }
            volver();
        }
    }

//    private void crearRenglones() {
//        renglones = new ArrayList<>();
//        Servicio servicio = trabajo.getServicio();
//        Rubro rubro = servicio.getRubro();
//        Estructura estructura = rubro.getEstructura();
////        es = null;
//        try {
////            es = new EstructuraServicioService().getAllEstructuraServicioByEstructuraActivos(estructura);
//        } catch (Exception ex) {
//            Logger.getLogger(ActualizarTrabajoFrame.class.getName()).log(Level.SEVERE, null, ex);
//        }
//        if (es != null && !es.isEmpty()) {
//            for (EstructuraServicio e : es) {
//                RenglonTrabajo rs = new RenglonTrabajo();
//                rs.setActivo(true);
//                rs.setCampo(e.getContenido());
//                rs.setCodigoCampo(e.getCampoEstructura());
//                rs.setContenido("");
//                rs.setFecha(new Date());
//                rs.setTrabajo(trabajo);
////                renglones.add(rs);
//            }
//        }
//    }
//    private void cargarCampos(int rowS) {
//        
//        Servicio servicio = servicios.get(rowS - 1);
//        caracteristicas = servicios.get(rowS - 1).getCaracteristicas();
//        if (servicios.get(rowS - 1).getBacteriologico() != null) {
//            if (servicios.get(rowS - 1).getBacteriologico()) {
//                bacterio = true;
//            } else {
//                bacterio = false;
//            }
//        } else {
//            bacterio = false;
//        }
//        Rubro rubro = servicio.getRubro();
//        Estructura estructura = rubro.getEstructura();
//        es = null;
//        try {
//            es = new EstructuraServicioService().getAllEstructuraServicioByEstructuraActivos(estructura);
//        } catch (Exception ex) {
//            Logger.getLogger(ActualizarTrabajoFrame.class.getName()).log(Level.SEVERE, null, ex);
//        }
//        if (es != null && !es.isEmpty()) {
//            DefaultTableModel tbl = (DefaultTableModel) tabla.getModel();
//            int rowH = 0;
//            int linO;
//            for (EstructuraServicio e : es) {
//                Object o[] = new Object[2];
//                o[0] = e.getContenido();
//                if (renglones != null && !renglones.isEmpty()) {
//                    RenglonTrabajo rs = renglones.get(rowH);
//                    if (rs.getContenido().isEmpty()) {
//                        o[1] = "";
//                    } else {
//                        int ce = renglones.get(rowS).getCodigoCampo();
//                        switch (ce) {
//                            case 1:
//                                o[1] = rs.getContenido();
//                                break;
//                            case 2:
//                                o[1] = rs.getContenido();
//                                break;
//                            case 3:
//                                o[1] = rs.getContenido();
//                                break;
//                            case 4:
//                                o[1] = rs.getContenido();
//                                break;
//                            case 5:
//                                o[1] = rs.getContenido();
//                                break;
//                            case 6:
//                                Long i = Long.valueOf(rs.getContenido());
//                                try {
//                                    o[1] = new PersonaService().getPersonaActivaById(i);
//                                } catch (Exception ex) {
//                                    Logger.getLogger(ActualizarTrabajoFrame.class.getName()).log(Level.SEVERE, null, ex);
//                                    o[1] = "X";
//                                }
//                                JOptionPane.showMessageDialog(this, "Xd");
//                                break;
//                            case 7:
//                                o[1] = rs.getContenido();
//                                break;
//                            case 8:
//                                o[1] = rs.getContenido();
//                                break;
//                            case 9:
//                                o[1] = rs.getContenido();
//                                break;
//                            case 10:
//                                linO = Integer.valueOf(rs.getContenido());
//                                if (linO == 1) {
//                                    o[1] = "SI";
//                                }
//                                if (linO == 2) {
//                                    o[1] = "NO";
//                                }
//                                break;
//                            case 11:
//                                linO = Integer.valueOf(rs.getContenido());
//                                if (linO == 1) {
//                                    o[1] = "SI";
//                                }
//                                if (linO == 2) {
//                                    o[1] = "NO";
//                                }
//                                break;
//                            case 12:
//                                linO = Integer.valueOf(rs.getContenido());
//                                if (linO == 1) {
//                                    o[1] = "SI";
//                                }
//                                if (linO == 2) {
//                                    o[1] = "NO";
//                                }
//                                break;
//                            default:
//                        }
//                    }
//                } else {
//                    o[1] = "";
//                }
//                tbl.addRow(o);
//                rowH += 1;
//            }
//            tabla.setModel(tbl);
//        }
//    }
    private void completar() {
        int row = tabla.getSelectedRow();
        if (row < 0) {
            JOptionPane.showMessageDialog(this, "SELECCIONE PARA COMPLETAR");
            return;
        }
        if (renglones != null && !renglones.isEmpty()) {
            int ce = renglones.get(row).getCodigoCampo();

            RenglonTrabajo re = renglones.get(row);
            String st = re.getContenido();
            CampoEstructura ce2 = CampoEstructura.fromCodigo(ce);
            ce2.visualizarCampos(comboP, fecha2Txt, textoTxt, cantidadTxt, importeTxt, comboO, personaLbl, fechaLbl, textoLbl, cantidadLbl, importeLbl, opcionLbl, st);

        }
        /*
        int row = tabla.getSelectedRow();
        if (row < 0) {
            JOptionPane.showMessageDialog(this, "SELECCIONE PARA COMPLETAR");
            return;
        }
        int ce = renglones.get(row).getCodigoCampo();
        RenglonTrabajo renglon = renglones.get(row);
        switch (ce) {
            case 1:
                fecha2Txt.setText(renglon.getContenido());
                fechaLbl.setVisible(true);
                fecha2Txt.setVisible(true);
                fecha2Txt.requestFocus();
                break;
            case 2:
                fecha2Txt.setText(renglon.getContenido());
                fechaLbl.setVisible(true);
                fecha2Txt.setVisible(true);
                fecha2Txt.requestFocus();
                break;
            case 3:
                fecha2Txt.setText(renglon.getContenido());
                fechaLbl.setVisible(true);
                fecha2Txt.setVisible(true);
                fecha2Txt.requestFocus();
                break;
            case 4:
                fecha2Txt.setText(renglon.getContenido());
                fechaLbl.setVisible(true);
                fecha2Txt.setVisible(true);
                fecha2Txt.requestFocus();
                break;
            case 5:
                fecha2Txt.setText(renglon.getContenido());
                fechaLbl.setVisible(true);
                fecha2Txt.setVisible(true);
                fecha2Txt.requestFocus();
                break;
            case 6:
                int i = 1;
                int pos = 0;
                if (!renglon.getContenido().trim().isEmpty()) {
                    String nombre = renglon.getContenido();
                    for (Persona p : personas) {
                        if (p.getApellidoNombre().equals(nombre)) {
                            pos = i;
                        }
                        i += 1;
                    }
                }
                comboP.setVisible(true);
                comboP.setSelectedIndex(pos);
                personaLbl.setVisible(true);
                comboP.requestFocus();
                comboP.addFocusListener(null);
                comboP.showPopup();
                break;
            case 7:
                textoLbl.setVisible(true);
                textoTxt.setVisible(true);
                textoTxt.setText(renglon.getContenido());
                textoTxt.requestFocus();
                break;
            case 8:
                importeLbl.setVisible(true);
                importeTxt.setVisible(true);
                importeTxt.setText(renglon.getContenido());
                importeTxt.requestFocus();
                break;
            case 9:
                cantidadLbl.setVisible(true);
                cantidadTxt.setVisible(true);
                cantidadTxt.setText(renglon.getContenido());
                cantidadTxt.requestFocus();
                break;
            case 10:
                if (renglon.getContenido().trim().isEmpty()) {
                    if (renglon.getContenido().equals("SI")) {
                        comboO.setSelectedIndex(1);
                    } else {
                        comboO.setSelectedIndex(2);
                    }
                }
                opcionLbl.setVisible(true);
                comboO.setVisible(true);
                comboO.requestFocus();
                break;
            case 11:
                if (renglon.getContenido().trim().isEmpty()) {
                    if (renglon.getContenido().equals("SI")) {
                        comboO.setSelectedIndex(1);
                    } else {
                        comboO.setSelectedIndex(2);
                    }
                }
                opcionLbl.setVisible(true);
                comboO.setVisible(true);
                comboO.requestFocus();
                break;
            case 12:
                if (renglon.getContenido().trim().isEmpty()) {
                    if (renglon.getContenido().equals("SI")) {
                        comboO.setSelectedIndex(1);
                    } else {
                        comboO.setSelectedIndex(2);
                    }
                }
                opcionLbl.setVisible(true);
                comboO.setVisible(true);
                comboO.requestFocus();
                break;
            case 13:
                textoLbl.setVisible(true);
                textoTxt.setVisible(true);
                textoTxt.setText(renglon.getContenido());
                textoTxt.requestFocus();
                break;
            case 14:
                break;
            case 15:
                opcionLbl.setVisible(true);
                comboO.setVisible(true);
                if (!renglon.getContenido().trim().isEmpty()) {
                    if (renglon.getContenido().equals("SI")) {
                        comboO.setSelectedIndex(1);
                    } else {
                        comboO.setSelectedIndex(2);
                    }
                }
                comboO.requestFocus();
                break;
            case 16:
                opcionLbl.setVisible(true);
                comboO.setVisible(true);
                if (!renglon.getContenido().trim().isEmpty()) {
                    if (renglon.getContenido().equals("SI")) {
                        comboO.setSelectedIndex(1);
                    } else {
                        comboO.setSelectedIndex(2);
                    }
                }
                comboO.requestFocus();
                break;
            default:
        }
         */
    }

    private boolean validar() {
        Servicio se = trabajo.getServicio();
        Consorcio cons = trabajo.getServicio().getConsorcio();
        Trabajo tra = null;
        try {
            tra = new TrabajoService().getTrabajoByConsorcioAndServicio(cons, se);
            if (tra != null) {
                for (RenglonTrabajo r : renglones) {
                    int codigo = r.getCodigoCampo();
                    if (codigo == 4) {
                        if (r.getContenido().trim().isEmpty()) {
                            JOptionPane.showMessageDialog(this, "TRABAJO SIN FECHA");
                            return false;
                        }
                    }
                    if (codigo == 15 || codigo == 16) {
                        if (r.getContenido().trim().isEmpty()) {
                            JOptionPane.showMessageDialog(this, "DEBE TENER UNA OPCION DE ANALISIS");
                            return false;
                        }
                    }
                    if (codigo == 11 || codigo == 10) {
                        if (r.getContenido().trim().isEmpty()) {
                            JOptionPane.showMessageDialog(this, "DEBE TENER UNA OPCION ENVIO O RECEPCION DE ANALISIS");
                            return false;
                        }
                    }
                }
            }
        } catch (Exception ex) {
            //Logger.getLogger(NuevoTrabajoFrame.class.getName()).log(Level.SEVERE, null, ex);
        }
        return true;
    }

    private void limpiarCampos() {
        //calleTxt.setText("");
        comboP.removeAllItems();
        comboP.addItem("");
        personas = null;
        try {
            personas = new PersonaService().getEmpleadosActivos();
        } catch (Exception ex) {
            Logger.getLogger(CompletarRenglonServicioFrame.class.getName()).log(Level.SEVERE, null, ex);
        }
        if (personas != null && !personas.isEmpty()) {
            for (Persona pe : personas) {
                comboP.addItem(pe.getApellidoNombre());
            }
        }
        comboO.removeAllItems();
        comboO.addItem("");
        comboO.addItem("SI");
        comboO.addItem("NO");
        ocultarCampos();
    }

    private void descartar() {
        limpiarCampos();
    }

    private void cargar() {
        int row = tabla.getSelectedRow();
        RenglonTrabajo renglon = renglones.get(row);
        int ce = renglones.get(row).getCodigoCampo();
        CampoEstructura campoEstr = CampoEstructura.fromCodigo(ce);
        String str = "";
        int linP = comboP.getSelectedIndex();
        int linO = comboO.getSelectedIndex();
        str = textoTxt.getText();
        campoEstr.cargarCampos(fecha2Txt,
                renglon, linP, personas, linO, str);

        renglones.set(row, renglon);
        tabla = UtilFrame.limpiarTabla(tabla);
        llenarTabla();
        limpiarCampos();
        tabla.requestFocus();
        /*
        int row = tabla.getSelectedRow();
        RenglonTrabajo renglon = renglones.get(row);
        int ce = renglones.get(row).getCodigoCampo();
//        System.out.println(ce);
//        System.out.println(renglones.get(row).getCampo());
//        JOptionPane.showMessageDialog(this, "X");
//        Date f = new Date();
        String str = "";
        int linO = 0;
        String fe = "";
        int largo = 0;
        switch (ce) {
            case 1:
                fe = fecha2Txt.getText();
                largo = fe.length();
                if (largo != 10) {
                    fe = fecha(fe);
                    return;
                }
                try {
                    fechaCargar = sdf.parse(fecha2Txt.getText());
                } catch (ParseException ex) {
                    Logger.getLogger(CompletarRenglonServicioFrame.class.getName()).log(Level.SEVERE, null, ex);
                    JOptionPane.showMessageDialog(this, "ERROR EN FECHA");
                    fecha2Txt.requestFocus();
                    return;
                }
                str = sdf.format(fechaCargar);
                renglon.setContenido(str);
                break;
            case 2:
                fe = fecha2Txt.getText();
                largo = fe.length();
                if (largo != 10) {
                    fe = fecha(fe);
                    return;
                }
                try {
                    fechaCargar = sdf.parse(fecha2Txt.getText());
                } catch (ParseException ex) {
                    Logger.getLogger(CompletarRenglonServicioFrame.class.getName()).log(Level.SEVERE, null, ex);
                    JOptionPane.showMessageDialog(this, "ERROR EN FECHA");
                    fecha2Txt.requestFocus();
                    return;
                }
                str = sdf.format(fechaCargar);
                renglon.setContenido(str);
                break;
            case 3:
                fe = fecha2Txt.getText();
                largo = fe.length();
                if (largo != 10) {
                    fe = fecha(fe);
                    return;
                }
                try {
                    fechaCargar = sdf.parse(fecha2Txt.getText());
                } catch (ParseException ex) {
                    Logger.getLogger(CompletarRenglonServicioFrame.class.getName()).log(Level.SEVERE, null, ex);
                    JOptionPane.showMessageDialog(this, "ERROR EN FECHA");
                    fecha2Txt.requestFocus();
                    return;
                }
                str = sdf.format(fechaCargar);
                renglon.setContenido(str);
                break;
            case 4:
                fe = fecha2Txt.getText();
                largo = fe.length();
                if (largo != 10) {
                    fe = fecha(fe);
                    return;
                }
                try {
                    fechaCargar = sdf.parse(fe);
                } catch (ParseException ex) {
                    Logger.getLogger(CompletarRenglonServicioFrame.class.getName()).log(Level.SEVERE, null, ex);
                    JOptionPane.showMessageDialog(this, "ERROR EN FECHA");
                    fecha2Txt.requestFocus();
                    return;
                }
                str = sdf.format(fechaCargar);
//                fechaCargar = f;
                renglon.setContenido(str);
                break;
            case 5:
                fe = fecha2Txt.getText();
                largo = fe.length();
                if (largo != 10) {
                    fe = fecha(fe);
                    return;
                }
                try {
                    fechaCargar = sdf.parse(fecha2Txt.getText());
                } catch (ParseException ex) {
                    Logger.getLogger(CompletarRenglonServicioFrame.class.getName()).log(Level.SEVERE, null, ex);
                    JOptionPane.showMessageDialog(this, "ERROR EN FECHA");
                    fecha2Txt.requestFocus();
                    return;
                }
                str = sdf.format(fechaCargar);
                renglon.setContenido(str);
                break;
            case 6:
                int linP = comboP.getSelectedIndex();
                if (linP < 1) {
                    JOptionPane.showMessageDialog(this, "SELECCIONE UNA PERSONA");
                    return;
                }
                Persona p = personas.get(linP - 1);
                str = p.getApellidoNombre();
                //str = p.getId().toString();
                renglon.setContenido(str);
                break;
            case 7:
                str = textoTxt.getText();
                renglon.setContenido(str);
                break;
            case 8:
                str = importeTxt.getText();
                renglon.setContenido(str);
                break;
            case 9:
                str = cantidadTxt.getText();
                renglon.setContenido(str);
                break;
            case 10:
                linO = comboO.getSelectedIndex();
                if (linO < 1) {
                    JOptionPane.showMessageDialog(this, "DEBE ELEGIR UNA OPCION");
                    return;
                }
                str = comboO.getSelectedItem().toString();
                renglon.setContenido(str);
                break;
            case 11:
                linO = comboO.getSelectedIndex();
                if (linO < 1) {
                    JOptionPane.showMessageDialog(this, "DEBE ELEGIR UNA OPCION");
                    return;
                }
                str = comboO.getSelectedItem().toString();
                renglon.setContenido(str);
                break;
            case 12:
                linO = comboO.getSelectedIndex();
                if (linO < 1) {
                    JOptionPane.showMessageDialog(this, "DEBE ELEGIR UNA OPCION");
                    return;
                }
                str = comboO.getSelectedItem().toString();
                renglon.setContenido(str);
                break;
            case 13:
                str = textoTxt.getText();
                renglon.setContenido(str);
                caracteristicas = str;
                break;
            case 14:
                str = textoTxt.getText();
                renglon.setContenido(str);
                break;
            case 15:
                linO = comboO.getSelectedIndex();
                if (linO < 1) {
                    JOptionPane.showMessageDialog(this, "DEBE ELEGIR UNA OPCION");
                    return;
                }
                str = comboO.getSelectedItem().toString();
                renglon.setContenido(str);
                break;
            case 16:
                linO = comboO.getSelectedIndex();
                if (linO < 1) {
                    JOptionPane.showMessageDialog(this, "DEBE ELEGIR UNA OPCION");
                    return;
                }
                str = comboO.getSelectedItem().toString();
                renglon.setContenido(str);
                break;
            default:
        }
        renglones.set(row, renglon);
        UtilFrame.limpiarTabla(tabla);
        cargarRenglones();
        //llenarTabla();
        limpiarCampos();
        tabla.requestFocus();
         */
    }

//    private void llenarTabla() {
//        DefaultTableModel tbl = (DefaultTableModel) tabla.getModel();
//        int rowH = 0;
//        int linO;
//        Long i = 0L;
////        System.out.println(es);
////        for (EstructuraServicio e : es) {
////            Object o[] = new Object[2];
////            o[0] = e.getContenido();
////            if (renglones != null && !renglones.isEmpty()) {
////                RenglonTrabajo rs = renglones.get(rowH);
////                if (rs.getContenido().isEmpty()) {
////                    o[1] = "";
////                } else {
////                    int ce = 1; //renglones.get(rowS).getCodigoCampo();
////                    System.out.println(ce);
////                    switch (ce) {
////                        case 1:
////                            o[1] = rs.getContenido();
//////                            System.out.println(rs.getContenido());
////                            break;
////                        case 2:
////                            o[1] = rs.getContenido();
//////                            System.out.println(rs.getContenido());
////                            break;
////                        case 3:
////                            o[1] = rs.getContenido();
//////                            System.out.println(rs.getContenido());
////                            break;
////                        case 4:
////                            o[1] = rs.getContenido();
//////                            i = Long.valueOf(rs.getContenido());
//////                            System.out.println(rs.getContenido());
//////                            try {
//////                                o[1] = new PersonaService().getPersonaActivaById(i);
////////                                System.out.println(new PersonaService().getPersonaActivaById(i));
//////                                
//////                            } catch (Exception ex) {
//////                                Logger.getLogger(NuevoTrabajoFrame.class.getName()).log(Level.SEVERE, null, ex);
//////                                o[1] = "X";
//////                            }
////                            break;
////                        case 5:
////                            o[1] = rs.getContenido();
//////                            System.out.println(rs.getContenido());
////                            break;
////                        case 6:
////                            i = Long.valueOf(rs.getContenido());
//////                            System.out.println(rs.getContenido());
////                            try {
////                                o[1] = new PersonaService().getPersonaActivaById(i);
//////                                System.out.println(new PersonaService().getPersonaActivaById(i));
////
////                            } catch (Exception ex) {
////                                Logger.getLogger(ActualizarTrabajoFrame.class.getName()).log(Level.SEVERE, null, ex);
////                                o[1] = "X";
////                            }
////                            JOptionPane.showMessageDialog(this, "Xs");
////                            break;
////                        case 7:
////                            o[1] = rs.getContenido();
//////                            System.out.println(rs.getContenido());
////                            break;
////                        case 8:
////                            o[1] = rs.getContenido();
//////                            System.out.println(rs.getContenido());
////                            break;
////                        case 9:
////                            o[1] = rs.getContenido();
//////                            System.out.println(rs.getContenido());
////                            break;
////                        case 10:
////                            linO = Integer.valueOf(rs.getContenido());
//////                            System.out.println(rs.getContenido());
////                            if (linO == 1) {
////                                o[1] = "SI";
////                            }
////                            if (linO == 2) {
////                                o[1] = "NO";
////                            }
////                            break;
////                        case 11:
////                            linO = Integer.valueOf(rs.getContenido());
//////                            System.out.println(rs.getContenido());
////                            if (linO == 1) {
////                                o[1] = "SI";
////                            }
////                            if (linO == 2) {
////                                o[1] = "NO";
////                            }
////                            break;
////                        case 12:
////                            linO = Integer.valueOf(rs.getContenido());
//////                            System.out.println(rs.getContenido());
////                            if (linO == 1) {
////                                o[1] = "SI";
////                            }
////                            if (linO == 2) {
////                                o[1] = "NO";
////                            }
////                            break;
////                        default:
////                    }
////                }
////            } else {
////                o[1] = "";
////            }
////            tbl.addRow(o);
////            rowH += 1;
////        }
//        tabla.setModel(tbl);
////        System.exit(0);
//    }
    private void volver() {
        MainFrame asf = new MainFrame();
        asf.setVisible(true);
        this.dispose();
    }

    private void ocultarCampos() {
        fechaLbl.setVisible(false);
        personaLbl.setVisible(false);
        textoLbl.setVisible(false);
        cantidadLbl.setVisible(false);
        importeLbl.setVisible(false);
        opcionLbl.setVisible(false);
        fecha2Txt.setVisible(false);
        comboP.setVisible(false);
        textoTxt.setVisible(false);
        cantidadTxt.setVisible(false);
        importeTxt.setVisible(false);
        comboO.setVisible(false);
        cargarBtn.setVisible(false);
        descartarBtn.setVisible(false);
        completarBtn.setVisible(false);
    }

    private void cargarRenglones() {
        if (renglones != null && !renglones.isEmpty()) {
            DefaultTableModel tbl = (DefaultTableModel) tabla.getModel();
            for (RenglonTrabajo rt : renglones) {
                Object o[] = new Object[2];
                o[0] = rt.getCampo();
                if (rt.getContenido().isEmpty()) {
                    o[1] = "";
                } else {
                    int ce = rt.getCodigoCampo();
                    CampoEstructura campoEstr = CampoEstructura.fromCodigo(ce);
                    String x1 = campoEstr.mostrarCampos(rt.getContenido());
                    o[1] = x1;
                }
                tbl.addRow(o);
            }
            tabla.setModel(tbl);
        }
    }

    private void llenarTabla() {
        DefaultTableModel tbl = (DefaultTableModel) tabla.getModel();
//        int rowH = 0;
//        for (EstructuraServicio e : es) {

//            o[0] = e.getContenido();
        if (renglones != null && !renglones.isEmpty()) {
            for (RenglonTrabajo rs : renglones) {
//                RenglonTrabajo rs = renglones.get(rowH);
                Object o[] = new Object[2];
                o[0] = rs.getCampo();
                if (rs.getContenido().isEmpty()) {
                    o[1] = "";
                } else {
                    int ce = rs.getCodigoCampo();
                    CampoEstructura campoEstr = CampoEstructura.fromCodigo(ce);
                    String x1 = campoEstr.mostrarCampos(rs.getContenido());
                    o[1] = x1;
                }
                tbl.addRow(o);
            }

        }
//        rowH += 1;
//        }
        tabla.setModel(tbl);
    }
}
