/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ar.com.ventas.frame;

import ar.com.ventas.entities.Abono;
import ar.com.ventas.entities.AbonoFactura;
import ar.com.ventas.entities.Administrador;
import ar.com.ventas.entities.AdministradorTitularCuitComprobante;
import ar.com.ventas.entities.Comprobante;
import ar.com.ventas.entities.ComprobanteRenglones;
import ar.com.ventas.entities.Consorcio;
import ar.com.ventas.entities.ConsorcioFactura;
import ar.com.ventas.entities.ConsorcioMaster;
import ar.com.ventas.entities.CuentaCorrienteCliente;
import ar.com.ventas.entities.Domicilio;
import ar.com.ventas.entities.Rubro;
import ar.com.ventas.entities.TitularCuit;
import ar.com.ventas.estructuras.Constantes;
import ar.com.ventas.main.MainFrame;
import ar.com.ventas.services.AbonoFacturaService;
import ar.com.ventas.services.AbonoService;
import ar.com.ventas.services.AdministradorTitularCuitComprobanteService;
import ar.com.ventas.services.ComprobanteRenglonesService;
import ar.com.ventas.services.ComprobanteService;
import ar.com.ventas.services.ConsorcioMasterService;
import ar.com.ventas.services.ConsorcioService;
import ar.com.ventas.services.CuentaCorrienteClienteService;
import ar.com.ventas.services.RubroService;
import ar.com.ventas.services.TitularCuitService;
import ar.com.ventas.util.UtilFrame;
import java.awt.Color;
import java.text.DecimalFormat;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Date;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Mario
 */
public class AsignarFacturaFrame extends javax.swing.JFrame {

    private List<Consorcio> consorcios;
    private List<Rubro> rubros;
    private List<Abono> abonosConsosNuevos;
    private List<ConsorcioFactura> facturas;
    private List<Comprobante> fcs;
    private SimpleDateFormat sdf = new SimpleDateFormat("dd/MM/yyyy");
    private DecimalFormat df = new DecimalFormat("#0.00");

    /**
     * Creates new form AsignarFacturaFrame
     */
    public AsignarFacturaFrame() {
        initComponents();
        getContentPane().setBackground(new java.awt.Color(Constantes.getR(), Constantes.getG(), Constantes.getB()));
        setExtendedState(6); // this.MAXIMIZED_BOTH
//        this.setLocationRelativeTo(null);
        limpiarCampos();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tabla = new javax.swing.JTable();
        asignarBtn = new javax.swing.JButton();
        volverBtn = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        filtroTxt = new javax.swing.JTextField();
        combo = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();
        deTxt = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        alTxt = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        comboR = new javax.swing.JComboBox<>();
        jLabel5 = new javax.swing.JLabel();
        adminTxt = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setTitle("ASIGNAR FACTURA A CONSORCIO");

        tabla.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "CONSORCIO", "CUIT", "ADMINISTRADOR", "FECH.FC", "NUMERO", "CTA", "RUB", "IMPORTE", "TITULAR", "M"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tabla);
        if (tabla.getColumnModel().getColumnCount() > 0) {
            tabla.getColumnModel().getColumn(0).setPreferredWidth(170);
            tabla.getColumnModel().getColumn(1).setPreferredWidth(40);
            tabla.getColumnModel().getColumn(2).setPreferredWidth(70);
            tabla.getColumnModel().getColumn(3).setPreferredWidth(20);
            tabla.getColumnModel().getColumn(4).setPreferredWidth(5);
            tabla.getColumnModel().getColumn(5).setPreferredWidth(5);
            tabla.getColumnModel().getColumn(7).setPreferredWidth(20);
            tabla.getColumnModel().getColumn(8).setPreferredWidth(90);
            tabla.getColumnModel().getColumn(9).setPreferredWidth(20);
        }

        asignarBtn.setText("Asignar");
        asignarBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                asignarBtnActionPerformed(evt);
            }
        });

        volverBtn.setText("Volver");
        volverBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                volverBtnActionPerformed(evt);
            }
        });

        jLabel1.setText("FILTRO CONSORCIO:");

        filtroTxt.setText("FILTRO");
        filtroTxt.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                filtroTxtKeyPressed(evt);
            }
        });

        combo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        combo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboActionPerformed(evt);
            }
        });

        jLabel2.setText("DESDE:");

        deTxt.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        deTxt.setText("DESDE");
        deTxt.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                deTxtKeyPressed(evt);
            }
        });

        jLabel3.setText("HASTA:");

        alTxt.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        alTxt.setText("HASTA");
        alTxt.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                alTxtKeyPressed(evt);
            }
        });

        jLabel4.setText("Rubro:");

        comboR.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        comboR.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboRActionPerformed(evt);
            }
        });
        comboR.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                comboRKeyPressed(evt);
            }
        });

        jLabel5.setText("ADMIN:");

        adminTxt.setText("ADMINISTRADOR");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 939, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(asignarBtn)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(volverBtn))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addGap(18, 18, 18)
                                .addComponent(filtroTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(deTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(alTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(42, 42, 42)
                                .addComponent(jLabel4)
                                .addGap(18, 18, 18)
                                .addComponent(comboR, javax.swing.GroupLayout.PREFERRED_SIZE, 270, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(combo, javax.swing.GroupLayout.PREFERRED_SIZE, 448, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLabel5)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(adminTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 276, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(deTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3)
                    .addComponent(alTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4)
                    .addComponent(comboR, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 366, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(filtroTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(combo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5)
                    .addComponent(adminTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(asignarBtn)
                    .addComponent(volverBtn))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void volverBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_volverBtnActionPerformed
        volver();
    }//GEN-LAST:event_volverBtnActionPerformed

    private void deTxtKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_deTxtKeyPressed
        if (evt.getKeyCode() == 10) {
            String fe = deTxt.getText();
            int largo = fe.length();
            if (largo == 10) {
                alTxt.requestFocus();
            } else {
                if (largo > 10) {
                    JOptionPane.showMessageDialog(this, "ERROR EN LARGO DE FECHA");
                    return;
                }
            }
            fe = UtilFrame.fecha(fe);
            deTxt.setText(fe);
        }
    }//GEN-LAST:event_deTxtKeyPressed

    private void alTxtKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_alTxtKeyPressed
        if (evt.getKeyCode() == 10) {
            String fe = alTxt.getText();
            int largo = fe.length();
            if (largo == 10) {
                comboR.addFocusListener(null);
                comboR.showPopup();
                comboR.requestFocus();
            } else {
                if (largo > 10) {
                    JOptionPane.showMessageDialog(this, "ERROR EN LARGO DE FECHA");
                    return;
                }
            }
            fe = UtilFrame.fecha(fe);
            alTxt.setText(fe);
        }
    }//GEN-LAST:event_alTxtKeyPressed

    private void filtroTxtKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_filtroTxtKeyPressed
        if (evt.getKeyCode() == 10) {
            if (!filtroTxt.getText().isEmpty()) {
                llenarCombo();
            }
        }
    }//GEN-LAST:event_filtroTxtKeyPressed

    private void asignarBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_asignarBtnActionPerformed
        asignar();
    }//GEN-LAST:event_asignarBtnActionPerformed

    private void comboRActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboRActionPerformed
        if (evt.getModifiers() == 16) {
            int rowR = comboR.getSelectedIndex();
            if (rowR > 0) {
                buscar();
            }
        }
    }//GEN-LAST:event_comboRActionPerformed

    private void comboRKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_comboRKeyPressed
        if (evt.getKeyCode() == 10) {
            int rowR = comboR.getSelectedIndex();
            if (rowR > 0) {
                buscar();
            }
        }
    }//GEN-LAST:event_comboRKeyPressed

    private void comboActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboActionPerformed
        int row = combo.getSelectedIndex();
        if (row > 0) {
            mostrar(row);
        }
    }//GEN-LAST:event_comboActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AsignarFacturaFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AsignarFacturaFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AsignarFacturaFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AsignarFacturaFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AsignarFacturaFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField adminTxt;
    private javax.swing.JTextField alTxt;
    private javax.swing.JButton asignarBtn;
    private javax.swing.JComboBox<String> combo;
    private javax.swing.JComboBox<String> comboR;
    private javax.swing.JTextField deTxt;
    private javax.swing.JTextField filtroTxt;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tabla;
    private javax.swing.JButton volverBtn;
    // End of variables declaration//GEN-END:variables

    private void volver() {
        MainFrame mf = new MainFrame();
        mf.setVisible(true);
        this.dispose();
    }

    private void buscar() {
        int rowR = comboR.getSelectedIndex();
        fcs = null;
        Date de = new Date();
        Date al = new Date();
        try {
            de = sdf.parse(deTxt.getText());
            al = sdf.parse(alTxt.getText());
        } catch (ParseException ex) {
            Logger.getLogger(AsignarFacturaFrame.class.getName()).log(Level.SEVERE, null, ex);
            JOptionPane.showMessageDialog(this, "ERROR FECHAS");
            return;
        }
        UtilFrame.limpiarTabla(tabla);
        try {
            if (rowR < 1) {
                fcs = new ComprobanteService().getComprobantesEntrFechasOrdenConsoParaAsignar(de, al);
            } else {
                Rubro ru = rubros.get(rowR - 1);
                fcs = new ComprobanteService().getComprobantesEntreFechasAndRubroParaAsignar(de, al, ru);
            }
        } catch (Exception ex) {
            Logger.getLogger(AsignarFacturaFrame.class.getName()).log(Level.SEVERE, null, ex);
        }
//        System.out.println(fcs);
//        System.exit(0);
        if (fcs != null && !fcs.isEmpty()) {
            facturas = new ArrayList<>();
            for (Comprobante comp : fcs) {
                Integer codigo = comp.getCodigoCliente();
                Consorcio cons = null;
                try {
                    cons = new ConsorcioService().getConsorcioByCodigo(codigo);
                } catch (Exception ex) {
                    Logger.getLogger(AsignarFacturaFrame.class.getName()).log(Level.SEVERE, null, ex);
                }
                ConsorcioFactura cnf = new ConsorcioFactura();
                cnf.setComprobante(comp);
                cnf.setConsorcio(cons);
                facturas.add(cnf);
            }
            fillTabla(facturas);
        }

//        consorcios = null;
//        
//        try {
//            consorcios = new ConsorcioService().getConsorciosActivosMaster();
//        } catch (Exception ex) {
//            Logger.getLogger(AsignarFacturaFrame.class.getName()).log(Level.SEVERE, null, ex);
//            JOptionPane.showMessageDialog(this, "ERROR");
//            return;
//        }
//        if (consorcios != null && !consorcios.isEmpty()) {
//
//            facturas = new ArrayList<>();
//            for (Consorcio co : consorcios) {
//                List<Comprobante> comprobantes = null;
//                try {
//                    comprobantes = new ComprobanteService().getComprobantesEntreFechasByConsorcio(co, de, al);
//                } catch (Exception ex) {
//                    Logger.getLogger(AsignarFacturaFrame.class.getName()).log(Level.SEVERE, null, ex);
//                }
//                if (comprobantes != null && !comprobantes.isEmpty()) {
//                    for (Comprobante cm : comprobantes) {
//                        Rubro rub = cm.getRubro();
//                        ConsorcioMaster coma = null;
//                        try {
//                            System.out.println(co);
//                            System.out.println(rub);
//                            coma = new ConsorcioMasterService().getConsorcioMasterByRubroAndConsorcio(rub, co);
//                            if (coma != null) {
//                                if (coma.getMaster() != null) {
//                                    if (coma.getMaster() > 0) {
//                                        continue;
//                                    }
//                                }
//                            }
//                            ConsorcioFactura cnf = new ConsorcioFactura();
//                            cnf.setComprobante(cm);
//                            cnf.setConsorcio(co);
//                            facturas.add(cnf);
//                        } catch (Exception ex) {
//                            Logger.getLogger(AsignarFacturaFrame.class.getName()).log(Level.SEVERE, null, ex);
//                        }
//
//                    }
//                }
//            }
//            fillTabla(facturas);
//
//        }
    }

    private void limpiarCampos() {
        deTxt.setText("");
        alTxt.setText("");
        filtroTxt.setText("");
        combo.removeAllItems();
        comboR.removeAllItems();
        comboR.addItem("");
        rubros = null;
        try {
            rubros = new RubroService().getAllRubrosActivos();
        } catch (Exception ex) {
            Logger.getLogger(AsignarFacturaFrame.class.getName()).log(Level.SEVERE, null, ex);
        }
        if (rubros != null && !rubros.isEmpty()) {
            for (Rubro r : rubros) {
                comboR.addItem(r.getDetalle());
            }
        }
    }

    private void llenarCombo() {
        int row = tabla.getSelectedRow();
        Comprobante co = null;
        if (row > -1) {
            co = facturas.get(row).getComprobante();
        } else {
            return;
        }
        String filtro = filtroTxt.getText();
        combo.removeAllItems();
        combo.addItem("");
        Rubro ru = co.getRubro();
        abonosConsosNuevos = null;
        try {
            abonosConsosNuevos = new AbonoService().getAbonosActivosByRubroAndFiltroConsorcio(filtro, ru);
//            consosNuevos = new ConsorcioService().getAllConsorciosActivosByFiltro(filtro);
        } catch (Exception ex) {
            Logger.getLogger(AsignarFacturaFrame.class.getName()).log(Level.SEVERE, null, ex);
//            System.out.println(filtro);
//            System.out.println(ru);
//            System.out.println(ru.getDetalle());
//            System.out.println(abonosConsosNuevos);
            JOptionPane.showMessageDialog(this, "CONSORCIOS NO ENCONTRADOS");
            return;
        }
        if (abonosConsosNuevos != null && !abonosConsosNuevos.isEmpty()) {
            for (Abono abo : abonosConsosNuevos) {
                String impo = df.format(abo.getImporte() / abo.getCuotas());
//                System.out.println(abo.getConsorcio());
//                System.out.println(abo.getCodigo());
//                System.out.println(abo.getConsorcio().getDomicilio());
                Domicilio dm = abo.getConsorcio().getDomicilio();
//                System.out.println(dm.getCalle());
//                System.out.println(dm.getNumero());
                combo.addItem(dm.getCalle() + " " + dm.getNumero() + " -----  $" + impo);
            }
            combo.addFocusListener(null);
            combo.showPopup();
            combo.requestFocus();
        }
    }

    private void asignar() {
        int row = combo.getSelectedIndex();
        int row0 = tabla.getSelectedRow();
        if (row < 1) {
            JOptionPane.showMessageDialog(this, "SELECCIONE UN CONSORCIO PARA ASIGNAR");
            return;
        }
        if (row0 < 0) {
            JOptionPane.showMessageDialog(this, "SELECCIONE UNA FACTURA PARA ASIGNAR");
            return;
        }
//        Comprobante comprobante = facturas.get(row0).getComprobante();
        Abono abono = abonosConsosNuevos.get(row - 1);
        Rubro rubro = abono.getRubro();

        Consorcio consorcio = facturas.get(row0).getConsorcio();
        Comprobante factura = facturas.get(row0).getComprobante();
//        int codigoConsorcio = consorcio.getCodigo();//tabla
        Consorcio consoNuevo = abono.getConsorcio();//combo
        if (abono.getPendiente()) {
            if (asignar2(consoNuevo, factura, consorcio)) {
//            System.out.println(consoNuevo.getId());
//            System.out.println(rubro.getDetalle());
//            System.out.println(consorcio.getDomicilio().getCalle());

                JOptionPane.showMessageDialog(this, "YA EXISTE FACTURA ASIGNADA");
                return;
            }
        } else {
            JOptionPane.showMessageDialog(this, "DEBE HABILITAR EL PERIODO PARA ESTA ASIGNACION");
            return;
        }

//        consoNuevo.setMaster(codigoConsorcio);
        Administrador admin = consoNuevo.getAdministrador();
        Long id_admin = admin.getId();
        TitularCuit titular = null;
        try {
            titular = new TitularCuitService().getTitularActivoByCuit(factura.getCuitTitular());
        } catch (Exception ex) {
            Logger.getLogger(AsignarFacturaFrame.class.getName()).log(Level.SEVERE, null, ex);
            JOptionPane.showMessageDialog(this, "ERROR EN TITULAR");
            return;
        }
//        Boolean existe;
//        existe = verificar(admin, factura);
////        System.exit(0);
//        if (!existe) {
////            System.out.println(existe);
//            JOptionPane.showMessageDialog(this, "ERROR EXISTE ADMINISTRACION");
//            return;
//        }
        int cuotaFacturada = abono.getCuotaFacturada();
        Comprobante cmpNuevo = new Comprobante();
//        System.out.println(consorcio.getDomicilio().getCalle() + consorcio.getDomicilio().getNumero());
        Domicilio dmN = consoNuevo.getDomicilio();
        String calleNueva = dmN.getCalle() + " " + dmN.getNumero();
        cmpNuevo.setCae(factura.getCae());
        cmpNuevo.setCalleNroPisoDtoCliente(calleNueva);
        cmpNuevo.setCantidadCuotas(factura.getCantidadCuotas());
        cmpNuevo.setCodigoCliente(consoNuevo.getCodigo());
        cmpNuevo.setCodigoComprobante(factura.getCodigoComprobante());
        cmpNuevo.setCodigoPostalAndLocalidadCliente(dmN.getCodigoPostal() + " " + dmN.getLocalidad());
        cmpNuevo.setCodigoPostalAndLocalidadTitular(factura.getCodigoPostalAndLocalidadTitular());
        cmpNuevo.setCuitCliente(factura.getCuitCliente());
        cmpNuevo.setCuitTitular(factura.getCuitTitular());
        cmpNuevo.setCuotasPagadas(cuotaFacturada + 1);
        cmpNuevo.setDomicilioTitular(factura.getDomicilioTitular());
        cmpNuevo.setFecha(factura.getFecha());
        cmpNuevo.setFechaInicioActividades(factura.getFechaInicioActividades());
        cmpNuevo.setFechaPeriodoDesde(factura.getFechaPeriodoDesde());
        cmpNuevo.setFechaPeriodoHasta(factura.getFechaPeriodoHasta());
        cmpNuevo.setFechaVencimientoCae(factura.getFechaVencimientoCae());
        cmpNuevo.setFechaVencimientoPago(factura.getFechaVencimientoPago());
        cmpNuevo.setGravado(factura.getGravado());
        cmpNuevo.setIibb(factura.getIibb());
        cmpNuevo.setIva(factura.getIva());
        cmpNuevo.setLetra(factura.getLetra());
        cmpNuevo.setLetraComprobanteAsociado(factura.getLetraComprobanteAsociado());
        cmpNuevo.setNumero(factura.getNumero());
        cmpNuevo.setNumeroComprobanteAsociado(factura.getNumeroComprobanteAsociado());
        cmpNuevo.setPagado(0.0);
        cmpNuevo.setPdfGenerado(false);
        cmpNuevo.setProductoServicio(factura.getProductoServicio());
        cmpNuevo.setProvinciaCliente(dmN.getProvincia());
        cmpNuevo.setProvinciaTitular(factura.getProvinciaTitular());
        cmpNuevo.setRazonSocialCliente(consoNuevo.getNombre());
        cmpNuevo.setRazonSocialTitular(factura.getRazonSocialTitular());
        cmpNuevo.setRubro(rubro);
        cmpNuevo.setSucursal(factura.getSucursal());
        cmpNuevo.setSucursalComprobanteAsociado(factura.getSucursalComprobanteAsociado());
        cmpNuevo.setTexto1(factura.getTexto1());
        cmpNuevo.setTexto2(factura.getTexto2());
        cmpNuevo.setTipoComprobanteAsociado(factura.getTipoComprobanteAsociado());
        cmpNuevo.setTipoDocumento(factura.getTipoDocumento());
        cmpNuevo.setTipoEmision(factura.getTipoEmision());
        cmpNuevo.setTipoInscripcion(factura.getTipoInscripcion());
        cmpNuevo.setTotal(factura.getTotal());
        cmpNuevo.setOriginal(false);
        cmpNuevo.setId_original(factura.getId());
        cmpNuevo.setId_administrador(id_admin);
        List<ComprobanteRenglones> renglones = null;
        abono.setCuotaFacturada(cuotaFacturada + 1);
        abono.setPendiente(false);
        try {
            renglones = new ComprobanteRenglonesService().getRenglonesPorComprobante(factura);
        } catch (Exception ex) {
            Logger.getLogger(AsignarFacturaFrame.class.getName()).log(Level.SEVERE, null, ex);
        }
        List<ComprobanteRenglones> renglonesNuevo = new ArrayList<>();
        if (renglones != null && !renglones.isEmpty()) {

            for (ComprobanteRenglones cr : renglones) {
                ComprobanteRenglones cr0 = new ComprobanteRenglones();
                cr0.setComprobante(cmpNuevo);
                cr0.setDetalle(cr.getDetalle());
                cr0.setImporte(cr.getImporte());
                renglonesNuevo.add(cr0);
            }
        } else {
            JOptionPane.showMessageDialog(this, "VERIFIQUE LA FACTURA NO TIENE RENGLONES");
            return;
        }
        Double saldo = consoNuevo.getSaldo();
        saldo += factura.getTotal();
        consoNuevo.setSaldo(saldo);
        AdministradorTitularCuitComprobante atcc = new AdministradorTitularCuitComprobante();
        atcc.setAdministrador(admin);
        atcc.setComprobante(factura);
        atcc.setTitular(titular);
        CuentaCorrienteCliente ccc = new CuentaCorrienteCliente();
        ccc.setComprobante(cmpNuevo);
        ccc.setConsorcio(consoNuevo);
        ccc.setDebe(factura.getTotal());
        ccc.setFecha(factura.getFecha());
        ccc.setHaber(0.0);
        ccc.setRecibo(null);
        ccc.setSaldo(saldo);
        ccc.setTipoComprobante(11);
        AbonoFactura af = new AbonoFactura();
        af.setAbono(abono);
        af.setActivo(true);
        af.setComprobante(factura);
        af.setTitular(titular);
        try {
            new AdministradorTitularCuitComprobanteService().saveFactura(atcc);
            new ConsorcioService().updateConsorcio(consoNuevo);
            cmpNuevo = new ComprobanteService().saveComprobante(cmpNuevo);
            ccc.setComprobante(cmpNuevo);
            new CuentaCorrienteClienteService().saveCuentaCorrienteCliente(ccc);
            for (ComprobanteRenglones cr1 : renglonesNuevo) {
                cr1.setComprobante(cmpNuevo);
                new ComprobanteRenglonesService().saveRenglon(cr1);
            }
            new AbonoService().updateAbono(abono);
            new AbonoFacturaService().saveAbonoFactura(af);
        } catch (Exception ex) {
            Logger.getLogger(AsignarFacturaFrame.class.getName()).log(Level.SEVERE, null, ex);
            JOptionPane.showMessageDialog(this, "ERROR EN PROCESOS DE ASIGNACION");
            return;
        }
        JOptionPane.showMessageDialog(this, "ASIGNACION COMPLETADA CORRECTAMENTE");
        volver();
    }

    private Boolean verificar(Administrador admin, Comprobante factura) {
        String cuitTitular = factura.getCuitTitular();
        List<AdministradorTitularCuitComprobante> atcc = null;
        try {
            atcc = new AdministradorTitularCuitComprobanteService().getExistenFacturas(factura, cuitTitular, admin);
        } catch (Exception ex) {
            Logger.getLogger(AsignarFacturaFrame.class.getName()).log(Level.SEVERE, null, ex);
//            System.out.println(atcc);
            return true;
        }
        if (atcc.isEmpty()) {
//            System.out.println(atcc);
            return true;
        } else {
//            System.out.println(atcc);
            return false;
        }
    }

    private void fillTabla(List<ConsorcioFactura> facturas) {
        DefaultTableModel tbl = (DefaultTableModel) tabla.getModel();
        if (facturas != null && !facturas.isEmpty()) {
            for (ConsorcioFactura cm : facturas) {
                Domicilio dm;
                String domi;
                String adm;
                String cuit;
                try {
                    dm = cm.getConsorcio().getDomicilio();
                    domi = dm.getCalle() + " " + dm.getNumero();
                    adm = cm.getConsorcio().getAdministrador().getNombreAdministrador();
                    cuit = cm.getConsorcio().getCuit();
                    Object o[] = new Object[10];
                    o[0] = domi;
                    o[1] = cuit;
                    o[2] = adm;
                    o[3] = sdf.format(cm.getComprobante().getFecha());
                    o[4] = cm.getComprobante().getNumero();
                    o[5] = cm.getComprobante().getCuotasPagadas();
                    o[6] = cm.getComprobante().getRubro().getDetalle();
                    o[7] = df.format(cm.getComprobante().getTotal());
                    o[8] = cm.getComprobante().getRazonSocialTitular();
                    if (cm.getComprobante().getOriginal() != null) {
                        if (cm.getComprobante().getOriginal()) {
                            o[9] = "M";
                        } else {
                            o[9] = "A";
                        }
                    } else {
                        o[9] = "M";
                    }
                    tbl.addRow(o);
                } catch (Exception ex) {
//                    System.out.println(cm.getConsorcio());
//                    System.out.println(cm);
//                    System.out.println(cm.getId());
//                    System.out.println(cm.getComprobante());
//                    System.exit(0);
                    dm = null;
                    domi = "ERR.CONSORCIO";
                    adm = "ERR.CONS.";
                    cuit = "ERR.CONS.";
                }

            }
            tabla.setModel(tbl);
        }
    }

    private Boolean asignar2(Consorcio consoNuevo, Comprobante factura, Consorcio consorcio) {
        String cuitTitular = factura.getCuitTitular();
        Administrador administrador = consoNuevo.getAdministrador();
        System.out.println(administrador.getId());
        System.out.println(administrador.getNombreAdministrador());
        System.out.println(factura.getNumero());
        System.out.println("");
        Integer numeroComprobante = factura.getNumero();
        Long id_adm = administrador.getId();
        List<Comprobante> comprobantes = null;
        Boolean hay = false;
        try {
            System.out.println(numeroComprobante);
            System.out.println(cuitTitular);
            System.out.println(id_adm);
            System.out.println("");
            comprobantes = new ComprobanteService().getComprobanteByNroAndTitular(numeroComprobante,
                    cuitTitular, id_adm);
        } catch (Exception ex) {
            Logger.getLogger(AsignarFacturaFrame.class.getName()).log(Level.SEVERE, null, ex);
        }
        System.out.println(comprobantes);

        if (comprobantes != null && !comprobantes.isEmpty()) {
            for (Comprobante co : comprobantes) {
                System.out.println(co.getFecha());
                System.out.println(co.getNumero());
                System.out.println(co.getRazonSocialTitular());
                System.out.println(co.getCalleNroPisoDtoCliente());
                System.out.println(co.getId_administrador());
                Administrador admNuevo = consoNuevo.getAdministrador();
                System.out.println(admNuevo.getNombreAdministrador());
                System.out.println(admNuevo.getId());
                Long id1 = admNuevo.getId();
                Long id2 = co.getId_administrador();
                System.out.println("");
                System.out.println(id1);
                System.out.println(id2);

                if (id1.equals(id2)) {
                    hay = true;
                }
            }

            System.out.println(hay);
//            System.exit(0);
            if (hay) {
                return true;
            } else {
                return false;
            }
        } else {
            return false;
        }

//        ConsorcioMaster cm = null;
//        try {
//            cm = new ConsorcioMasterService().getConsorcioActivoMaster(consorcio, rubro, consoNuevo);
//        } catch (Exception ex) {
//            Logger.getLogger(AsignarFacturaFrame.class.getName()).log(Level.SEVERE, null, ex);
//        }
//        if (cm != null) {
//            return true;
//        } else {
//            Integer codigo = consorcio.getCodigo();
//            ConsorcioMaster cm1 = new ConsorcioMaster();
//            cm1.setActivo(true);
//            cm1.setRubro(rubro);
//            cm1.setConsorcio(consoNuevo);
//            cm1.setMaster(codigo);
//            try {
//                new ConsorcioMasterService().saveConsorcioMaster(cm1);
//            } catch (Exception ex) {
//                Logger.getLogger(AsignarFacturaFrame.class.getName()).log(Level.SEVERE, null, ex);
//            }
//            return false;
//        }
    }

    private void mostrar(int row) {
        Abono abono = abonosConsosNuevos.get(row - 1);
        Consorcio consoNuevo = abono.getConsorcio();//combo
        String admi = consoNuevo.getAdministrador().getNombreAdministrador();

        adminTxt.setText(admi);
    }
}
