/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ar.com.ventas.frame;

import ar.com.ventas.entities.Persona;
import ar.com.ventas.entities.RenglonTrabajo;
import ar.com.ventas.entities.Trabajo;
import ar.com.ventas.estructuras.Constantes;
import ar.com.ventas.services.PersonaService;
import java.text.DecimalFormat;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author Mario
 */
public class CompletarRenglonServicioFrame extends javax.swing.JFrame {

    private SimpleDateFormat sdf = new SimpleDateFormat("dd/MM/yyyy");
    private Integer row;
    private Integer rowC;
    private Integer rowT;
    private List<RenglonTrabajo> renglones;
    private List<Persona> personas;
    private Trabajo servicio;

    /**
     * Creates new form CompletarRenglonServicioFrame
     *
     * @param servicio
     * @param row
     * @param rowC
     * @param rowT
     * @param renglones
     */
    public CompletarRenglonServicioFrame(Trabajo servicio, Integer row, Integer rowC, Integer rowT, List<RenglonTrabajo> renglones) {
        initComponents();
        getContentPane().setBackground(new java.awt.Color(Constantes.getR(), Constantes.getG(), Constantes.getB()));
        this.setLocationRelativeTo(null);
//        setExtendedState(this.MAXIMIZED_BOTH);
        this.servicio = servicio;
        this.row = row;
        this.rowC = rowC;
        this.rowT = rowT;
        this.renglones = renglones;
        limpiarCampos();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        volverBtn = new javax.swing.JButton();
        guardarBtn = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        campoTxt = new javax.swing.JTextField();
        ingreseFechaLbl = new javax.swing.JLabel();
        ingresePersonaLbl = new javax.swing.JLabel();
        ingreseTextoLbl = new javax.swing.JLabel();
        ingreseCantidadLbl = new javax.swing.JLabel();
        ingreseImporteLbl = new javax.swing.JLabel();
        confirmeOpcionLbl = new javax.swing.JLabel();
        fechaTxt = new javax.swing.JTextField();
        comboP = new javax.swing.JComboBox<>();
        textoTxt = new javax.swing.JTextField();
        cantidadTxt = new javax.swing.JTextField();
        importeTxt = new javax.swing.JTextField();
        comboO = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setTitle("COMPLETAR CAMPO");

        volverBtn.setText("Volver");
        volverBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                volverBtnActionPerformed(evt);
            }
        });

        guardarBtn.setText("Guardar");
        guardarBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                guardarBtnActionPerformed(evt);
            }
        });

        jLabel1.setText("Campo a Completar:");

        campoTxt.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        campoTxt.setText("CAMPO");

        ingreseFechaLbl.setText("Ingrese Fecha:");

        ingresePersonaLbl.setText("Ingrese Persona:");

        ingreseTextoLbl.setText("Ingrese Texto:");

        ingreseCantidadLbl.setText("Ingrese Cantidad:");

        ingreseImporteLbl.setText("Ingrese Importe:");

        confirmeOpcionLbl.setText("Confirme Opción:");

        fechaTxt.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        fechaTxt.setText("FECHA");

        comboP.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        textoTxt.setText("TEXTO");

        cantidadTxt.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        cantidadTxt.setText("CANTIDAD");

        importeTxt.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        importeTxt.setText("IMPORTE");

        comboO.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(guardarBtn)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(volverBtn))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(ingreseFechaLbl)
                            .addComponent(ingresePersonaLbl)
                            .addComponent(ingreseTextoLbl)
                            .addComponent(ingreseCantidadLbl)
                            .addComponent(ingreseImporteLbl)
                            .addComponent(confirmeOpcionLbl))
                        .addGap(33, 33, 33)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(campoTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 618, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(fechaTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cantidadTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(importeTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(comboO, javax.swing.GroupLayout.PREFERRED_SIZE, 207, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(textoTxt, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(comboP, javax.swing.GroupLayout.Alignment.LEADING, 0, 580, Short.MAX_VALUE)))
                        .addGap(0, 138, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(campoTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ingreseFechaLbl)
                    .addComponent(fechaTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ingresePersonaLbl)
                    .addComponent(comboP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ingreseTextoLbl)
                    .addComponent(textoTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ingreseCantidadLbl)
                    .addComponent(cantidadTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ingreseImporteLbl)
                    .addComponent(importeTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(confirmeOpcionLbl)
                    .addComponent(comboO, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 221, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(volverBtn)
                    .addComponent(guardarBtn))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void volverBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_volverBtnActionPerformed
        volver();
    }//GEN-LAST:event_volverBtnActionPerformed

    private void guardarBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_guardarBtnActionPerformed
        guardar();
    }//GEN-LAST:event_guardarBtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CompletarRenglonServicioFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CompletarRenglonServicioFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CompletarRenglonServicioFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CompletarRenglonServicioFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CompletarRenglonServicioFrame(null, null, null, null, null).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField campoTxt;
    private javax.swing.JTextField cantidadTxt;
    private javax.swing.JComboBox<String> comboO;
    private javax.swing.JComboBox<String> comboP;
    private javax.swing.JLabel confirmeOpcionLbl;
    private javax.swing.JTextField fechaTxt;
    private javax.swing.JButton guardarBtn;
    private javax.swing.JTextField importeTxt;
    private javax.swing.JLabel ingreseCantidadLbl;
    private javax.swing.JLabel ingreseFechaLbl;
    private javax.swing.JLabel ingreseImporteLbl;
    private javax.swing.JLabel ingresePersonaLbl;
    private javax.swing.JLabel ingreseTextoLbl;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JTextField textoTxt;
    private javax.swing.JButton volverBtn;
    // End of variables declaration//GEN-END:variables

    private void limpiarCampos() {
        ocultarTodo();
        llenarCombo();
//        campoTxt.setText(row.toString());
//        System.out.println(servicio);
//        System.out.println(rowC);
//        System.exit(0);
        campoTxt.setText(renglones.get(row).getCampo());
        int ce = renglones.get(row).getCodigoCampo();
        switch (ce) {
            case 1:
                fechaTxt.setText("");
                ingreseFechaLbl.setVisible(true);
                fechaTxt.setVisible(true);
                fechaTxt.requestFocus();
                break;
            case 2:
                fechaTxt.setText("");
                ingreseFechaLbl.setVisible(true);
                fechaTxt.setVisible(true);
                fechaTxt.requestFocus();
                break;
            case 3:
                fechaTxt.setText("");
                ingreseFechaLbl.setVisible(true);
                fechaTxt.setVisible(true);
                fechaTxt.requestFocus();
                break;
            case 4:
                fechaTxt.setText("");
                ingreseFechaLbl.setVisible(true);
                fechaTxt.setVisible(true);
                fechaTxt.requestFocus();
                break;
            case 5:
                fechaTxt.setText("");
                ingreseFechaLbl.setVisible(true);
                fechaTxt.setVisible(true);
                fechaTxt.requestFocus();
                break;
            case 6:
                ingresePersonaLbl.setVisible(true);
                comboP.setVisible(true);
                comboP.requestFocus();
                break;
            case 7:
                ingreseTextoLbl.setVisible(true);
                textoTxt.setVisible(true);
                textoTxt.setText("");
                textoTxt.requestFocus();
                break;
            case 8:
                ingreseImporteLbl.setVisible(true);
                importeTxt.setVisible(true);
                importeTxt.setText("");
                importeTxt.requestFocus();
                break;
            case 9:
                ingreseCantidadLbl.setVisible(true);
                cantidadTxt.setVisible(true);
                cantidadTxt.setText("");
                cantidadTxt.requestFocus();
                break;
            case 10:
                confirmeOpcionLbl.setVisible(true);
                comboO.setVisible(true);
                comboO.requestFocus();
                break;
            case 11:
                confirmeOpcionLbl.setVisible(true);
                comboO.setVisible(true);
                comboO.requestFocus();
                break;
            case 12:
                confirmeOpcionLbl.setVisible(true);
                comboO.setVisible(true);
                comboO.requestFocus();
                break;
            default:
        }
    }

    private void ocultarTodo() {
        ingreseFechaLbl.setVisible(false);
        ingresePersonaLbl.setVisible(false);
        ingreseTextoLbl.setVisible(false);
        ingreseCantidadLbl.setVisible(false);
        ingreseImporteLbl.setVisible(false);
        confirmeOpcionLbl.setVisible(false);
        fechaTxt.setVisible(false);
        comboP.setVisible(false);
        textoTxt.setVisible(false);
        cantidadTxt.setVisible(false);
        importeTxt.setVisible(false);
        comboO.setVisible(false);
    }

    private void llenarCombo() {
        comboP.removeAllItems();
        comboP.addItem("");
        personas = null;
        try {
            personas = new PersonaService().getAllPersonasActivas();
        } catch (Exception ex) {
            Logger.getLogger(CompletarRenglonServicioFrame.class.getName()).log(Level.SEVERE, null, ex);
        }
        if (personas != null && !personas.isEmpty()) {
            for (Persona pe : personas) {
                comboP.addItem(pe.getApellidoNombre());
            }
        }
        comboO.removeAllItems();
        comboO.addItem("");
        comboO.addItem("SI");
        comboO.addItem("NO");
    }

    private void volver() {
        NuevoTrabajoFrame nsf = new NuevoTrabajoFrame();
        nsf.setVisible(true);
        this.dispose();
    }

    private void guardar() {
        if (validar()) {
            RenglonTrabajo renglon = renglones.get(row);
            int ce = renglones.get(row).getCodigoCampo();
            Date f = new Date();
            String str;
            Integer linO;
            switch (ce) {
                case 1:
                    try {
                        f = sdf.parse(fechaTxt.getText());
                    } catch (ParseException ex) {
                        Logger.getLogger(CompletarRenglonServicioFrame.class.getName()).log(Level.SEVERE, null, ex);
                        JOptionPane.showMessageDialog(this, "ERROR EN FECHA");
                        fechaTxt.requestFocus();
                        return;
                    }
                    str = sdf.format(f);
                    renglon.setContenido(str);
                    break;
                case 2:
                    try {
                        f = sdf.parse(fechaTxt.getText());
                    } catch (ParseException ex) {
                        Logger.getLogger(CompletarRenglonServicioFrame.class.getName()).log(Level.SEVERE, null, ex);
                        JOptionPane.showMessageDialog(this, "ERROR EN FECHA");
                        fechaTxt.requestFocus();
                        return;
                    }
                    str = sdf.format(f);
                    renglon.setContenido(str);
                    break;
                case 3:
                    try {
                        f = sdf.parse(fechaTxt.getText());
                    } catch (ParseException ex) {
                        Logger.getLogger(CompletarRenglonServicioFrame.class.getName()).log(Level.SEVERE, null, ex);
                        JOptionPane.showMessageDialog(this, "ERROR EN FECHA");
                        fechaTxt.requestFocus();
                        return;
                    }
                    str = sdf.format(f);
                    renglon.setContenido(str);
                    break;
                case 4:
                    try {
                        f = sdf.parse(fechaTxt.getText());
                    } catch (ParseException ex) {
                        Logger.getLogger(CompletarRenglonServicioFrame.class.getName()).log(Level.SEVERE, null, ex);
                        JOptionPane.showMessageDialog(this, "ERROR EN FECHA");
                        fechaTxt.requestFocus();
                        return;
                    }
                    str = sdf.format(f);
                    renglon.setContenido(str);
                    break;
                case 5:
                    try {
                        f = sdf.parse(fechaTxt.getText());
                    } catch (ParseException ex) {
                        Logger.getLogger(CompletarRenglonServicioFrame.class.getName()).log(Level.SEVERE, null, ex);
                        JOptionPane.showMessageDialog(this, "ERROR EN FECHA");
                        fechaTxt.requestFocus();
                        return;
                    }
                    str = sdf.format(f);
                    renglon.setContenido(str);
                    break;
                case 6:
                    int linP = comboP.getSelectedIndex();
                    if (linP < 1) {
                        JOptionPane.showMessageDialog(this, "SELECCIONE UNA PERSONA");
                        return;
                    }
                    Persona p = personas.get(linP - 1);
                    str = p.getId().toString();
                    renglon.setContenido(str);
                    break;
                case 7:
                    str = textoTxt.getText();
                    renglon.setContenido(str);
                    break;
                case 8:
                    str = importeTxt.getText();
                    renglon.setContenido(str);
                    break;
                case 9:
                    str = cantidadTxt.getText();
                    renglon.setContenido(str);
                    break;
                case 10:
                    linO = comboO.getSelectedIndex();
                    if(linO < 1){
                        JOptionPane.showMessageDialog(this, "DEBE ELEGIR UNA OPCION");
                        return;
                    }
                    str = String.valueOf(linO);
                    renglon.setContenido(str);
                    break;
                case 11:
                    linO = comboO.getSelectedIndex();
                    if(linO < 1){
                        JOptionPane.showMessageDialog(this, "DEBE ELEGIR UNA OPCION");
                        return;
                    }
                    str = String.valueOf(linO);
                    renglon.setContenido(str);
                    break;
                case 12:
                    linO = comboO.getSelectedIndex();
                    if(linO < 1){
                        JOptionPane.showMessageDialog(this, "DEBE ELEGIR UNA OPCION");
                        return;
                    }
                    str = String.valueOf(linO);
                    renglon.setContenido(str);
                    break;
                default:
            }
            renglones.set(row, renglon);
            volver();
        }
    }

    private boolean validar() {
        return true;
    }
}
