/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ar.com.ventas.frame;

import ar.com.ventas.entities.Consorcio;
import ar.com.ventas.entities.CuentaCorrienteCliente;
import ar.com.ventas.entities.Domicilio;
import ar.com.ventas.estructuras.Constantes;
import ar.com.ventas.main.MainFrame;
import ar.com.ventas.services.ConsorcioService;
import ar.com.ventas.services.CuentaCorrienteClienteService;
import ar.com.ventas.util.UtilFrame;
import java.text.DecimalFormat;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Mario
 */
public class CuentaCorrienteClienteFrame1 extends javax.swing.JFrame {

    private List<Consorcio> consorcios;
    private DecimalFormat df = new DecimalFormat("#0.00");
    private DecimalFormat dfs = new DecimalFormat("0000");
    private DecimalFormat dfn = new DecimalFormat("00000000");
    private SimpleDateFormat sdf = new SimpleDateFormat("dd/MM/yyyy");

    /**
     * Creates new form CuentaCorrienteClienteFrame
     */
    public CuentaCorrienteClienteFrame1() {
        initComponents();
        getContentPane().setBackground(new java.awt.Color(Constantes.getR(), Constantes.getG(), Constantes.getB()));
//        this.setLocationRelativeTo(null);
        setExtendedState(this.MAXIMIZED_BOTH);
        limpiarCampos();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel4 = new javax.swing.JLabel();
        deTxt = new javax.swing.JTextField();
        alTxt = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabla = new javax.swing.JTable();
        volverBtn = new javax.swing.JButton();
        excelBtn = new javax.swing.JButton();
        verCpbteBtn = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setTitle("VER CUENTA CORRIENTE ORDENADO POR CONSORCIO");

        jLabel4.setText("DESDE:");

        deTxt.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        deTxt.setText("DESDE");
        deTxt.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                deTxtKeyPressed(evt);
            }
        });

        alTxt.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        alTxt.setText("HASTA");
        alTxt.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                alTxtKeyPressed(evt);
            }
        });

        jLabel5.setText("HASTA:");

        tabla.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "FECHA", "CONSORCIO", "RUBRO", "COMPROBANTE", "CUOTA", "DEBE", "HABER", "SALDO"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tabla);

        volverBtn.setText("Volver");
        volverBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                volverBtnActionPerformed(evt);
            }
        });

        excelBtn.setText("Excel");
        excelBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                excelBtnActionPerformed(evt);
            }
        });

        verCpbteBtn.setText("Ver Cpbte");
        verCpbteBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                verCpbteBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 909, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(deTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(alTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(excelBtn)
                        .addGap(18, 18, 18)
                        .addComponent(verCpbteBtn)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(volverBtn)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(deTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5)
                    .addComponent(alTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 365, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(volverBtn)
                    .addComponent(excelBtn)
                    .addComponent(verCpbteBtn))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void deTxtKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_deTxtKeyPressed
        if (evt.getKeyCode() == 10) {
            String fe = deTxt.getText();
            int largo = fe.length();
            if (largo == 10) {
                alTxt.requestFocus();
            }
            fe = UtilFrame.fecha(fe);
            deTxt.setText(fe);
        }

    }//GEN-LAST:event_deTxtKeyPressed

    private void alTxtKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_alTxtKeyPressed
        if (evt.getKeyCode() == 10) {
            String fe = alTxt.getText();
            int largo = fe.length();
            if (largo == 10) {
                llenarTabla();
            }
            fe = UtilFrame.fecha(fe);
            alTxt.setText(fe);
        }
    }//GEN-LAST:event_alTxtKeyPressed

    private void volverBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_volverBtnActionPerformed
        volver();
    }//GEN-LAST:event_volverBtnActionPerformed

    private void excelBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_excelBtnActionPerformed
        excel();
    }//GEN-LAST:event_excelBtnActionPerformed

    private void verCpbteBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_verCpbteBtnActionPerformed
        verCpbte();
    }//GEN-LAST:event_verCpbteBtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CuentaCorrienteClienteFrame1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CuentaCorrienteClienteFrame1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CuentaCorrienteClienteFrame1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CuentaCorrienteClienteFrame1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CuentaCorrienteClienteFrame1().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField alTxt;
    private javax.swing.JTextField deTxt;
    private javax.swing.JButton excelBtn;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tabla;
    private javax.swing.JButton verCpbteBtn;
    private javax.swing.JButton volverBtn;
    // End of variables declaration//GEN-END:variables

    private void limpiarCampos() {
//        filtroTxt.setText("");
//        saldoTxt.setText("");
        deTxt.setText("");
        alTxt.setText("");
//        combo.removeAllItems();
//        combo.addItem("");
    }

//    private void llenarCombo() {
//        String filtro = filtroTxt.getText();
//        consorcios = null;
//        try {
//            consorcios = new ConsorcioService().getAllConsorciosActivosByFiltro(filtro);
//        } catch (Exception ex) {
//            Logger.getLogger(CuentaCorrienteClienteFrame1.class.getName()).log(Level.SEVERE, null, ex);
//        }
//        combo.removeAllItems();
//        combo.addItem("");
//        if (consorcios != null && !consorcios.isEmpty()) {
//            for (Consorcio co : consorcios) {
//                Domicilio dm = co.getDomicilio();
//                String cons = dm.getCalle() + " " + dm.getNumero();
//                combo.addItem(cons);
//            }
//            combo.addFocusListener(null);
//            combo.showPopup();
//            combo.requestFocus();
//        }
//    }
    private void datosConsorcio(int row) {
        Consorcio consorcio = consorcios.get(row - 1);
        if (consorcio.getSaldo() != null) {
//            System.out.println(consorcio.getSaldo());
//            System.out.println(consorcio.getDomicilio().getCalle());
//            System.exit(0);
        } else {

        }
        UtilFrame.limpiarTabla(tabla);
        deTxt.requestFocus();
    }

    private void llenarTabla() {
        Date de = new Date();
        Date al = new Date();
        try {
            de = sdf.parse(deTxt.getText());
            al = sdf.parse(alTxt.getText());
        } catch (ParseException ex) {
            Logger.getLogger(CuentaCorrienteClienteFrame1.class.getName()).log(Level.SEVERE, null, ex);
        }
        consorcios = null;
        try {
            consorcios = new ConsorcioService().getAllConsorciosActivos();
        } catch (Exception ex) {
            Logger.getLogger(CuentaCorrienteClienteFrame1.class.getName()).log(Level.SEVERE, null, ex);
        }
        UtilFrame.limpiarTabla(tabla);
        for (Consorcio c : consorcios) {
            List<CuentaCorrienteCliente> ccc = null;
            try {
                ccc = new CuentaCorrienteClienteService().getCuentaCorrienteClienteByClienteEntreFechas(c, de, al);
            } catch (Exception ex) {
                Logger.getLogger(CuentaCorrienteClienteFrame1.class.getName()).log(Level.SEVERE, null, ex);
            }
            if (ccc != null && !ccc.isEmpty()) {
                DefaultTableModel tbl = (DefaultTableModel) tabla.getModel();
                for (CuentaCorrienteCliente cc : ccc) {
                    Object o[] = new Object[8];
                    o[0] = sdf.format(cc.getFecha());
                    int tipo = cc.getTipoComprobante();
                    String cpbte = "ND ";
                    if (tipo == 11) {
                        cpbte = "FC ";
                    }
                    if (tipo == 13) {
                        cpbte = "NC ";
                    }
                    if (tipo < 4) {
                        cpbte += cc.getComprobante().getLetra() + " "
                                + dfs.format(cc.getComprobante().getSucursal()) + "-"
                                + dfn.format(cc.getComprobante().getNumero());
                    }
                    Domicilio dm = cc.getConsorcio().getDomicilio();
                    String rub = cc.getComprobante().getRubro().getDetalle();
                    o[1] = dm.getCalle() + " " + dm.getNumero();
                    o[2] = rub;
                    o[3] = cpbte;
                    String cuota = cc.getComprobante().getCuotasPagadas().toString();
                    o[4] = cuota;
                    o[5] = df.format(cc.getDebe());
                    o[6] = df.format(cc.getHaber());
                    o[7] = df.format(cc.getSaldo());
                    tbl.addRow(o);
                }
                tabla.setModel(tbl);
            }
        }
    }

    private void volver() {
        MainFrame mf = new MainFrame();
        mf.setVisible(true);
        this.dispose();
    }

//    private void ingresarCobranza() {
//        int row = combo.getSelectedIndex();
//        if (row > 0) {
//            Consorcio consorcio = consorcios.get(row - 1);
//            Date fecha = new Date();
//            try {
//                fecha = sdf.parse(fechaPagoTxt.getText());
//            } catch (ParseException ex) {
//                Logger.getLogger(CuentaCorrienteClienteFrame.class.getName()).log(Level.SEVERE, null, ex);
//                JOptionPane.showMessageDialog(this, "ERROR EN LA FECHA");
//                return;
//            }
//            Double impt;
//            try {
//                impt = Double.valueOf(importeAbonadoTxt.getText().replace(",", "."));
//            } catch (Exception ex) {
//                JOptionPane.showMessageDialog(this, "ERROR EN IMPORTE");
//                return;
//            }
//            int v = UtilFrame.asignarPagoToConsorcio(consorcio, fecha, impt);
//            if (v == 1) {
//                importeAbonadoTxt.setText("");
//                fechaPagoTxt.setText("");
//                volverBtn.requestFocus();
//                JOptionPane.showMessageDialog(this, "RECIBO GUARDADO CORRECTAMENTE");
//                llenarTabla();
//                return;
//            }
//            JOptionPane.showMessageDialog(this, "ERROR GUARDANDO RECIBO");
//        }
//    }
    private void excel() {
        
    }

    private void verCpbte() {
        
    }
}
