/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ar.com.ventas.frame;

import ar.com.ventas.entities.Consorcio;
import ar.com.ventas.entities.FacturaDeTercero;
import ar.com.ventas.estructuras.Constantes;
import ar.com.ventas.services.FacturaDeTerceroService;
import java.text.DecimalFormat;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author Mario
 */
public class ModificarFacturaTerceroFrame extends javax.swing.JFrame {

    private Consorcio consorcio;
    private SimpleDateFormat sdf = new SimpleDateFormat("dd/MM/yyyy");
    private DecimalFormat df = new DecimalFormat("#0.00");
    private FacturaDeTercero factura;

    /**
     * Creates new form NuevaFacturaTerceroFrame
     *
     * @param consorcio
     * @param factura
     */
    public ModificarFacturaTerceroFrame(Consorcio consorcio, FacturaDeTercero factura) {
        initComponents();
        getContentPane().setBackground(new java.awt.Color(Constantes.getR(), Constantes.getG(), Constantes.getB()));
        this.setLocationRelativeTo(null);
//        setExtendedState(this.MAXIMIZED_BOTH);
        this.consorcio = consorcio;
        this.factura = factura;
        llenarCampos();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        consorcioTxt = new javax.swing.JTextField();
        fechaTxt = new javax.swing.JTextField();
        numeroTxt = new javax.swing.JTextField();
        proveedorTxt = new javax.swing.JTextField();
        totalTxt = new javax.swing.JTextField();
        guardarBtn = new javax.swing.JButton();
        volverBtn = new javax.swing.JButton();
        entregadaChk = new javax.swing.JCheckBox();
        cobradoChk = new javax.swing.JCheckBox();
        cobradoTxt = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setTitle("MODIFICAR FACTURA DE TERCEROS");

        jLabel1.setText("Consorcio:");

        jLabel2.setText("Fecha:");

        jLabel3.setText("Número:");

        jLabel4.setText("Proveedor:");

        jLabel5.setText("Total Factura:");

        consorcioTxt.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        consorcioTxt.setText("CONSORCIO");

        fechaTxt.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        fechaTxt.setText("FECHA");
        fechaTxt.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                fechaTxtKeyPressed(evt);
            }
        });

        numeroTxt.setText("NUMERO");
        numeroTxt.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                numeroTxtKeyPressed(evt);
            }
        });

        proveedorTxt.setText("PROVEEDOR");
        proveedorTxt.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                proveedorTxtKeyPressed(evt);
            }
        });

        totalTxt.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        totalTxt.setText("TOTAL");

        guardarBtn.setText("Guardar");
        guardarBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                guardarBtnActionPerformed(evt);
            }
        });

        volverBtn.setText("Volver");
        volverBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                volverBtnActionPerformed(evt);
            }
        });

        entregadaChk.setText("Entregada");

        cobradoChk.setText("Cobrada");

        cobradoTxt.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        cobradoTxt.setText("COBRADO");

        jLabel6.setText("Cobrado:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(guardarBtn)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(volverBtn))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(cobradoChk)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel1)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel4)
                                    .addComponent(jLabel5)
                                    .addComponent(entregadaChk))
                                .addGap(24, 24, 24)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(consorcioTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 594, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addComponent(numeroTxt, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 145, Short.MAX_VALUE)
                                        .addComponent(fechaTxt, javax.swing.GroupLayout.Alignment.LEADING))
                                    .addComponent(proveedorTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 399, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(totalTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(jLabel6)
                                        .addGap(18, 18, 18)
                                        .addComponent(cobradoTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                        .addGap(0, 183, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(consorcioTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(fechaTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(numeroTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(proveedorTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(totalTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cobradoTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6))
                .addGap(18, 18, 18)
                .addComponent(entregadaChk)
                .addGap(18, 18, 18)
                .addComponent(cobradoChk)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 242, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(guardarBtn)
                    .addComponent(volverBtn))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void guardarBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_guardarBtnActionPerformed
        guardar();
    }//GEN-LAST:event_guardarBtnActionPerformed

    private void volverBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_volverBtnActionPerformed
        volver();
    }//GEN-LAST:event_volverBtnActionPerformed

    private void fechaTxtKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_fechaTxtKeyPressed
        if (evt.getKeyCode() == 10) {
            if (fechaTxt.getText().isEmpty()) {
                fechaTxt.setText(sdf.format(new Date()));
            } else {
                numeroTxt.requestFocus();
            }
        }
    }//GEN-LAST:event_fechaTxtKeyPressed

    private void numeroTxtKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_numeroTxtKeyPressed
        if (evt.getKeyCode() == 10) {
            if (!numeroTxt.getText().isEmpty()) {
                proveedorTxt.requestFocus();
            }
        }
    }//GEN-LAST:event_numeroTxtKeyPressed

    private void proveedorTxtKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_proveedorTxtKeyPressed
        if (evt.getKeyCode() == 10) {
            if (!proveedorTxt.getText().isEmpty()) {
                totalTxt.requestFocus();
            }
        }
    }//GEN-LAST:event_proveedorTxtKeyPressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ModificarFacturaTerceroFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ModificarFacturaTerceroFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ModificarFacturaTerceroFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ModificarFacturaTerceroFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ModificarFacturaTerceroFrame(null, null).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JCheckBox cobradoChk;
    private javax.swing.JTextField cobradoTxt;
    private javax.swing.JTextField consorcioTxt;
    private javax.swing.JCheckBox entregadaChk;
    private javax.swing.JTextField fechaTxt;
    private javax.swing.JButton guardarBtn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JTextField numeroTxt;
    private javax.swing.JTextField proveedorTxt;
    private javax.swing.JTextField totalTxt;
    private javax.swing.JButton volverBtn;
    // End of variables declaration//GEN-END:variables

    private void guardar() {
        if (validar()) {
            if (cobradoChk.isSelected()) {
                factura.setCobrada(true);
                Double pesos = Double.valueOf(totalTxt.getText().replace(",", "."));
                factura.setTotal(pesos);
                factura.setImporteCobrado(pesos);
            } else {
                factura.setCobrada(false);
                Double pesos = Double.valueOf(totalTxt.getText().replace(",", "."));
                Double pesosCobrados = Double.valueOf(cobradoTxt.getText().replace(",", "."));
                factura.setTotal(pesos);
                factura.setImporteCobrado(pesosCobrados);
            }
            factura.setConsorcio(consorcio);
            if (entregadaChk.isSelected()) {
                factura.setEntregada(true);
            } else {
                factura.setEntregada(false);
            }
            Date fecha = new Date();
            try {
                fecha = sdf.parse(fechaTxt.getText());
            } catch (ParseException ex) {
                Logger.getLogger(ModificarFacturaTerceroFrame.class.getName()).log(Level.SEVERE, null, ex);
                JOptionPane.showMessageDialog(this, "ERROR Nro 266 FECHA FACTURA\nUTILICE DD/MM/AAAA");
                return;
            }
            factura.setFecha(fecha);
            factura.setProveedor(proveedorTxt.getText());
            Integer numero = Integer.valueOf(numeroTxt.getText());
            factura.setNumero(numero);
            try {
                new FacturaDeTerceroService().updateFacturaDeTercero(factura);
                JOptionPane.showMessageDialog(this, "FACTURA ACTUALIZADA CORRECTAMENTE");
            } catch (Exception ex) {
                Logger.getLogger(ModificarFacturaTerceroFrame.class.getName()).log(Level.SEVERE, null, ex);
                JOptionPane.showMessageDialog(this, "ERROR Nro.289 GUARDANDO FACTURA");
                return;
            }
            volver();
        }
    }

    private void volver() {
        FacturasTerceroFrame ftf = new FacturasTerceroFrame();
        ftf.setVisible(true);
        this.dispose();
    }

    private void llenarCampos() {
        consorcioTxt.setText(consorcio.getNombre() + " "
                + consorcio.getDomicilio().getCalle() + " "
                + consorcio.getDomicilio().getNumero());
        consorcioTxt.setEditable(false);
        if (factura.getEntregada()) {
            entregadaChk.setSelected(true);
        } else {
            entregadaChk.setSelected(false);
        }
        if (factura.getCobrada()) {
            cobradoChk.setSelected(true);
        } else {
            cobradoChk.setSelected(false);
        }
        proveedorTxt.setText(factura.getProveedor());
        totalTxt.setText(df.format(factura.getTotal()));
        fechaTxt.setText(sdf.format(factura.getFecha()));
        numeroTxt.setText(factura.getNumero().toString());
        fechaTxt.requestFocus();
        cobradoTxt.setText(df.format(factura.getImporteCobrado()));
    }

    private boolean validar() {
        if (fechaTxt.getText().isEmpty()) {
            JOptionPane.showMessageDialog(this, "DEBE ESCRIBIR UNA FECHA");
            fechaTxt.requestFocus();
            return false;
        }
        if (numeroTxt.getText().isEmpty()) {
            JOptionPane.showMessageDialog(this, "DEBE ESCRIBIR UN NUMERO DE FACTURA");
            numeroTxt.requestFocus();
            return false;
        }
        if (proveedorTxt.getText().isEmpty()) {
            JOptionPane.showMessageDialog(this, "DEBE ESCRIBIR UN PROVEEDOR DE FACTURA");
            proveedorTxt.requestFocus();
            return false;
        }
        if (totalTxt.getText().isEmpty()) {
            JOptionPane.showMessageDialog(this, "DEBE ESCRIBIR UN TOTAL DE FACTURA");
            totalTxt.requestFocus();
            return false;
        }
        return true;
    }
}
