/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ar.com.ventas.frame;

import ar.com.ventas.entities.Administrador;
import ar.com.ventas.entities.Consorcio;
import ar.com.ventas.entities.Domicilio;
import ar.com.ventas.estructuras.Constantes;
import ar.com.ventas.estructuras.TipoDocumento;
import ar.com.ventas.estructuras.TipoResponsable;
import ar.com.ventas.services.AdministradorService;
import ar.com.ventas.services.ConsorcioService;
import java.util.ArrayList;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author Mario
 */
public class NuevoConsorcioFrame extends javax.swing.JFrame {

    private List<Administrador> administradores;
    private Integer codigo = 0;
    private List<TipoResponsable> tiposInscripcion = new ArrayList<>();
    private List<TipoDocumento> tiposDocumento = new ArrayList<>();

    /**
     * Creates new form NuevoConsorcioFrame
     */
    public NuevoConsorcioFrame() {
        initComponents();
        getContentPane().setBackground(new java.awt.Color(Constantes.getR(), Constantes.getG(), Constantes.getB()));
        this.setLocationRelativeTo(null);
//        setExtendedState(this.MAXIMIZED_BOTH);
        limpiarCampos();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        observacionesTxt = new javax.swing.JTextArea();
        guardarBtn = new javax.swing.JButton();
        volverBtn = new javax.swing.JButton();
        razonSocialTxt = new javax.swing.JTextField();
        calleTxt = new javax.swing.JTextField();
        numeroTxt = new javax.swing.JTextField();
        codigoPostalTxt = new javax.swing.JTextField();
        provinciaTxt = new javax.swing.JTextField();
        localidadTxt = new javax.swing.JTextField();
        encargadoTxt = new javax.swing.JTextField();
        telefonoEncargadoTxt = new javax.swing.JTextField();
        horarioEncargadoTxt = new javax.swing.JTextField();
        telefonoEncargado1Txt = new javax.swing.JTextField();
        telefonoPorteriaTxt = new javax.swing.JTextField();
        encargado1Txt = new javax.swing.JTextField();
        horarioEncargado1Txt = new javax.swing.JTextField();
        telefonoConsejoTxt = new javax.swing.JTextField();
        cantidadPisosTxt = new javax.swing.JTextField();
        cantidadDptosTxt = new javax.swing.JTextField();
        comboI = new javax.swing.JComboBox<>();
        comboD = new javax.swing.JComboBox<>();
        comboA = new javax.swing.JComboBox<>();
        jLabel24 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        jLabel28 = new javax.swing.JLabel();
        cuitTxt = new javax.swing.JTextField();
        jLabel29 = new javax.swing.JLabel();
        jLabel30 = new javax.swing.JLabel();
        jLabel31 = new javax.swing.JLabel();
        jLabel32 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setTitle("NUEVO CONSORCIO");

        jLabel1.setText("Razón Social:");

        jLabel2.setText("Calle:");

        jLabel3.setText("Número:");

        jLabel4.setText("Código Postal:");

        jLabel5.setText("Localidad:");

        jLabel6.setText("Provincia:");

        jLabel7.setText("Tipo Inscripción:");

        jLabel8.setText("Tipo Documento:");

        jLabel9.setText("Encargado:");

        jLabel10.setText("Horario Encargado:");

        jLabel11.setText("Teléfono Encargado:");

        jLabel12.setText("Encargado 1:");

        jLabel13.setText("Horario Encargado 1:");

        jLabel14.setText("Teléfono Encargado 1:");

        jLabel18.setText("Teléfono Portería:");

        jLabel19.setText("Administrador:");

        jLabel20.setText("Teléfono/Nombre Consejo:");

        jLabel21.setText("Cantidad Pisos:");

        jLabel22.setText("Cantidad Departamentos:");

        jLabel23.setText("Observaciones:");

        observacionesTxt.setColumns(20);
        observacionesTxt.setRows(5);
        jScrollPane1.setViewportView(observacionesTxt);

        guardarBtn.setText("Guardar");
        guardarBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                guardarBtnActionPerformed(evt);
            }
        });

        volverBtn.setText("Volver");
        volverBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                volverBtnActionPerformed(evt);
            }
        });

        razonSocialTxt.setText("RAZON SOCIAL");
        razonSocialTxt.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                razonSocialTxtKeyPressed(evt);
            }
        });

        calleTxt.setText("CALLE");
        calleTxt.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                calleTxtKeyPressed(evt);
            }
        });

        numeroTxt.setText("NUMERO");
        numeroTxt.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                numeroTxtKeyPressed(evt);
            }
        });

        codigoPostalTxt.setText("C.POSTAL");
        codigoPostalTxt.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                codigoPostalTxtKeyPressed(evt);
            }
        });

        provinciaTxt.setText("PROVINCIA");
        provinciaTxt.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                provinciaTxtKeyPressed(evt);
            }
        });

        localidadTxt.setText("LOCALIDAD");
        localidadTxt.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                localidadTxtKeyPressed(evt);
            }
        });

        encargadoTxt.setText("ENCARGADO");
        encargadoTxt.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                encargadoTxtKeyPressed(evt);
            }
        });

        telefonoEncargadoTxt.setText("TELEFONO ENCARGADO");
        telefonoEncargadoTxt.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                telefonoEncargadoTxtKeyPressed(evt);
            }
        });

        horarioEncargadoTxt.setText("HORARIO ENCARGADO");
        horarioEncargadoTxt.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                horarioEncargadoTxtKeyPressed(evt);
            }
        });

        telefonoEncargado1Txt.setText("TELEFONO ENCARGADO 1");
        telefonoEncargado1Txt.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                telefonoEncargado1TxtKeyPressed(evt);
            }
        });

        telefonoPorteriaTxt.setText("TELEFONO PORTERIA");
        telefonoPorteriaTxt.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                telefonoPorteriaTxtKeyPressed(evt);
            }
        });

        encargado1Txt.setText("ENCARGADO 1");
        encargado1Txt.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                encargado1TxtKeyPressed(evt);
            }
        });

        horarioEncargado1Txt.setText("HORARIO ENCARGADO 1");
        horarioEncargado1Txt.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                horarioEncargado1TxtKeyPressed(evt);
            }
        });

        telefonoConsejoTxt.setText("TELEFONO CONSEJO");
        telefonoConsejoTxt.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                telefonoConsejoTxtKeyPressed(evt);
            }
        });

        cantidadPisosTxt.setText("CAN PISOS");
        cantidadPisosTxt.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                cantidadPisosTxtKeyPressed(evt);
            }
        });

        cantidadDptosTxt.setText("CAN DTPOS");
        cantidadDptosTxt.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                cantidadDptosTxtKeyPressed(evt);
            }
        });

        comboI.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        comboI.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboIActionPerformed(evt);
            }
        });

        comboD.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        comboA.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        comboA.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboAActionPerformed(evt);
            }
        });

        jLabel24.setText("*");

        jLabel25.setText("*");

        jLabel26.setText("*");

        jLabel27.setText("*");

        jLabel28.setText("CUIT:");

        cuitTxt.setText("CUIT");
        cuitTxt.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                cuitTxtKeyPressed(evt);
            }
        });

        jLabel29.setText("*");

        jLabel30.setText("*");

        jLabel31.setText("*");

        jLabel32.setText("*");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(guardarBtn)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(volverBtn))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                                .addComponent(jLabel14)
                                                .addGap(18, 18, 18)
                                                .addComponent(telefonoEncargado1Txt))
                                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(jLabel11)
                                                    .addComponent(jLabel12))
                                                .addGap(18, 18, 18)
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addGroup(layout.createSequentialGroup()
                                                        .addComponent(encargado1Txt, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                        .addComponent(jLabel13))
                                                    .addComponent(telefonoEncargadoTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 373, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(jLabel18)
                                                    .addComponent(jLabel19))
                                                .addGap(40, 40, 40)
                                                .addComponent(telefonoPorteriaTxt)))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(horarioEncargado1Txt, javax.swing.GroupLayout.DEFAULT_SIZE, 140, Short.MAX_VALUE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel21)
                                        .addGap(33, 33, 33)
                                        .addComponent(cantidadPisosTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(106, 106, 106)
                                        .addComponent(jLabel22)
                                        .addGap(18, 18, 18)
                                        .addComponent(cantidadDptosTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel23)
                                        .addGap(18, 18, 18)
                                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 486, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel6)
                                            .addComponent(jLabel9)
                                            .addComponent(jLabel7))
                                        .addGap(28, 28, 28)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(encargadoTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 196, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(29, 29, 29)
                                                .addComponent(jLabel10)
                                                .addGap(29, 29, 29)
                                                .addComponent(horarioEncargadoTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addGroup(layout.createSequentialGroup()
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                                    .addComponent(comboI, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                    .addComponent(provinciaTxt, javax.swing.GroupLayout.DEFAULT_SIZE, 241, Short.MAX_VALUE))
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addGroup(layout.createSequentialGroup()
                                                        .addComponent(jLabel29)
                                                        .addGap(20, 20, 20)
                                                        .addComponent(jLabel28)
                                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                        .addComponent(cuitTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 192, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                    .addGroup(layout.createSequentialGroup()
                                                        .addComponent(jLabel30)
                                                        .addGap(15, 15, 15)
                                                        .addComponent(jLabel8)
                                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                        .addComponent(comboD, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel20)
                                        .addGap(18, 18, 18)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(comboA, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(telefonoConsejoTxt, javax.swing.GroupLayout.DEFAULT_SIZE, 364, Short.MAX_VALUE))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jLabel32)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel31))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel1)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel4))
                                .addGap(37, 37, 37)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(calleTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 411, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jLabel26)
                                        .addGap(18, 18, 18)
                                        .addComponent(jLabel3)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(numeroTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jLabel25))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(razonSocialTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 458, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jLabel24))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(codigoPostalTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(jLabel5)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(localidadTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 241, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jLabel27)))))
                        .addGap(0, 247, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(razonSocialTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel24))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3)
                    .addComponent(calleTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(numeroTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel25)
                    .addComponent(jLabel26))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(codigoPostalTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5)
                    .addComponent(localidadTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel27))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(provinciaTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel28)
                    .addComponent(cuitTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel29))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel7)
                        .addComponent(jLabel8)
                        .addComponent(comboD, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel31))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(comboI, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel30)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(jLabel10)
                    .addComponent(encargadoTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(horarioEncargadoTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(telefonoEncargadoTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12)
                    .addComponent(jLabel13)
                    .addComponent(encargado1Txt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(horarioEncargado1Txt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel14)
                    .addComponent(telefonoEncargado1Txt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel18)
                    .addComponent(telefonoPorteriaTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel19)
                    .addComponent(comboA, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel32))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel20)
                    .addComponent(telefonoConsejoTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel21)
                    .addComponent(jLabel22)
                    .addComponent(cantidadPisosTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cantidadDptosTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel23))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(guardarBtn)
                    .addComponent(volverBtn))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void razonSocialTxtKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_razonSocialTxtKeyPressed
        if (evt.getKeyCode() == 10) {
            if (!razonSocialTxt.getText().isEmpty()) {
                calleTxt.requestFocus();
            }
        }
    }//GEN-LAST:event_razonSocialTxtKeyPressed

    private void calleTxtKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_calleTxtKeyPressed
        if (evt.getKeyCode() == 10) {
            if (!calleTxt.getText().isEmpty()) {
                numeroTxt.requestFocus();
            }
        }
    }//GEN-LAST:event_calleTxtKeyPressed

    private void numeroTxtKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_numeroTxtKeyPressed
        if (evt.getKeyCode() == 10) {
            if (!numeroTxt.getText().isEmpty()) {
                codigoPostalTxt.requestFocus();
            }
        }
    }//GEN-LAST:event_numeroTxtKeyPressed

    private void codigoPostalTxtKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_codigoPostalTxtKeyPressed
        if (evt.getKeyCode() == 10) {
            localidadTxt.requestFocus();
        }
    }//GEN-LAST:event_codigoPostalTxtKeyPressed

    private void localidadTxtKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_localidadTxtKeyPressed
        if (evt.getKeyCode() == 10) {
            if (!localidadTxt.getText().isEmpty()) {
                provinciaTxt.requestFocus();
            }
        }
    }//GEN-LAST:event_localidadTxtKeyPressed

    private void provinciaTxtKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_provinciaTxtKeyPressed
        if (evt.getKeyCode() == 10) {
            if (!provinciaTxt.getText().isEmpty()) {
                cuitTxt.requestFocus();
            }
        }
    }//GEN-LAST:event_provinciaTxtKeyPressed

    private void encargadoTxtKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_encargadoTxtKeyPressed
        if (evt.getKeyCode() == 10) {
            horarioEncargadoTxt.requestFocus();
        }
    }//GEN-LAST:event_encargadoTxtKeyPressed

    private void horarioEncargadoTxtKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_horarioEncargadoTxtKeyPressed
        if (evt.getKeyCode() == 10) {
            telefonoEncargadoTxt.requestFocus();
        }
    }//GEN-LAST:event_horarioEncargadoTxtKeyPressed

    private void telefonoEncargadoTxtKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_telefonoEncargadoTxtKeyPressed
        if (evt.getKeyCode() == 10) {
            encargado1Txt.requestFocus();
        }
    }//GEN-LAST:event_telefonoEncargadoTxtKeyPressed

    private void encargado1TxtKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_encargado1TxtKeyPressed
        if (evt.getKeyCode() == 10) {
            horarioEncargado1Txt.requestFocus();
        }
    }//GEN-LAST:event_encargado1TxtKeyPressed

    private void horarioEncargado1TxtKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_horarioEncargado1TxtKeyPressed
        if (evt.getKeyCode() == 10) {
            telefonoEncargado1Txt.requestFocus();

        }
    }//GEN-LAST:event_horarioEncargado1TxtKeyPressed

    private void telefonoEncargado1TxtKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_telefonoEncargado1TxtKeyPressed
        if (evt.getKeyCode() == 10) {
            telefonoPorteriaTxt.requestFocus();
        }
    }//GEN-LAST:event_telefonoEncargado1TxtKeyPressed

    private void telefonoPorteriaTxtKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_telefonoPorteriaTxtKeyPressed
        if (evt.getKeyCode() == 10) {
            telefonoConsejoTxt.requestFocus();
        }
    }//GEN-LAST:event_telefonoPorteriaTxtKeyPressed

    private void telefonoConsejoTxtKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_telefonoConsejoTxtKeyPressed
        if (evt.getKeyCode() == 10) {
            cantidadPisosTxt.requestFocus();
        }
    }//GEN-LAST:event_telefonoConsejoTxtKeyPressed

    private void cantidadPisosTxtKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_cantidadPisosTxtKeyPressed
        if (evt.getKeyCode() == 10) {
            cantidadDptosTxt.requestFocus();
        }
    }//GEN-LAST:event_cantidadPisosTxtKeyPressed

    private void cantidadDptosTxtKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_cantidadDptosTxtKeyPressed
        if (evt.getKeyCode() == 10) {
            observacionesTxt.requestFocus();
        }
    }//GEN-LAST:event_cantidadDptosTxtKeyPressed

    private void guardarBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_guardarBtnActionPerformed
        guardar();
    }//GEN-LAST:event_guardarBtnActionPerformed

    private void volverBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_volverBtnActionPerformed
        volver();
    }//GEN-LAST:event_volverBtnActionPerformed

    private void comboIActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboIActionPerformed
        int row = comboI.getSelectedIndex();
        if (row > 0) {
            if (TipoResponsable.CONSUMFINAL.getCodigo().equals(5)) {
                if (cuitTxt.getText().isEmpty()) {
                    cuitTxt.setText("00-00000000-0");
                    comboD.setSelectedIndex(7);
                } else {
                    comboD.setSelectedIndex(2);
                }
                encargadoTxt.requestFocus();
            }
        }
    }//GEN-LAST:event_comboIActionPerformed

    private void cuitTxtKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_cuitTxtKeyPressed
        if (evt.getKeyCode() == 10) {
            encargadoTxt.requestFocus();
        }
    }//GEN-LAST:event_cuitTxtKeyPressed

    private void comboAActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboAActionPerformed
        int row = comboA.getSelectedIndex();
        if(row>0){
            telefonoConsejoTxt.requestFocus();
        }
    }//GEN-LAST:event_comboAActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(NuevoConsorcioFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(NuevoConsorcioFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(NuevoConsorcioFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(NuevoConsorcioFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new NuevoConsorcioFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField calleTxt;
    private javax.swing.JTextField cantidadDptosTxt;
    private javax.swing.JTextField cantidadPisosTxt;
    private javax.swing.JTextField codigoPostalTxt;
    private javax.swing.JComboBox<String> comboA;
    private javax.swing.JComboBox<String> comboD;
    private javax.swing.JComboBox<String> comboI;
    private javax.swing.JTextField cuitTxt;
    private javax.swing.JTextField encargado1Txt;
    private javax.swing.JTextField encargadoTxt;
    private javax.swing.JButton guardarBtn;
    private javax.swing.JTextField horarioEncargado1Txt;
    private javax.swing.JTextField horarioEncargadoTxt;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField localidadTxt;
    private javax.swing.JTextField numeroTxt;
    private javax.swing.JTextArea observacionesTxt;
    private javax.swing.JTextField provinciaTxt;
    private javax.swing.JTextField razonSocialTxt;
    private javax.swing.JTextField telefonoConsejoTxt;
    private javax.swing.JTextField telefonoEncargado1Txt;
    private javax.swing.JTextField telefonoEncargadoTxt;
    private javax.swing.JTextField telefonoPorteriaTxt;
    private javax.swing.JButton volverBtn;
    // End of variables declaration//GEN-END:variables

    private void limpiarCampos() {
        llenarCombos();
        razonSocialTxt.setText("CONSORCIO DE PROPIETARIOS");
        calleTxt.setText("");
        numeroTxt.setText("");
        codigoPostalTxt.setText("");
        localidadTxt.setText("C.A.B.A.");
        provinciaTxt.setText("CAPITAL FEDERAL");
        cuitTxt.setText("");
        encargadoTxt.setText("");
        horarioEncargadoTxt.setText("");
        telefonoEncargadoTxt.setText("");
        encargado1Txt.setText("");
        horarioEncargado1Txt.setText("");
        telefonoEncargado1Txt.setText("");
        telefonoPorteriaTxt.setText("");
        telefonoConsejoTxt.setText("");
        cantidadPisosTxt.setText("");
        cantidadDptosTxt.setText("");
        observacionesTxt.setText("");
        calleTxt.requestFocus();
    }

    private void volver() {
        AbmConsorcioFrame acf = new AbmConsorcioFrame();
        acf.setVisible(true);
        this.dispose();
    }

    private void guardar() {
        if (validar()) {
            int rowA = comboA.getSelectedIndex();
            Administrador administrador = administradores.get(rowA - 1);
            Consorcio consorcio = new Consorcio();
            Domicilio domicilio = new Domicilio();
            consorcio.setActivo(true);
            consorcio.setAdministrador(administrador);
            if (!cantidadDptosTxt.getText().isEmpty()) {
                Integer cd = Integer.valueOf(cantidadDptosTxt.getText());
                consorcio.setCantidadDepartamentos(cd);
            } else {
                consorcio.setCantidadDepartamentos(0);
            }
            if (!cantidadPisosTxt.getText().isEmpty()) {
                Integer cp = Integer.valueOf(cantidadPisosTxt.getText());
                consorcio.setCantidadPisos(cp);
            } else {
                consorcio.setCantidadPisos(0);
            }
            consorcio.setCodigo(codigo);
            consorcio.setCuit(cuitTxt.getText());
            int rowD = comboD.getSelectedIndex();
            consorcio.setDocumentoTipo(tiposDocumento.get(rowD - 1).getCodigo());
            domicilio.setCalle(calleTxt.getText());
            domicilio.setCodigoPostal(codigoPostalTxt.getText());
            domicilio.setLocalidad(localidadTxt.getText());
            domicilio.setNumero(numeroTxt.getText());
            domicilio.setPisoDto("");
            domicilio.setProvincia(provinciaTxt.getText());
            consorcio.setDomicilio(domicilio);
            consorcio.setSaldo(0.0);
//            consorcio.setMaster(0);
            consorcio.setEncargado(encargadoTxt.getText());
            consorcio.setEncargado1(encargado1Txt.getText());
            consorcio.setHorarioEncargado(horarioEncargadoTxt.getText());
            consorcio.setHorarioEncargado1(horarioEncargado1Txt.getText());
            consorcio.setNombre(razonSocialTxt.getText());
            consorcio.setObservaciones(observacionesTxt.getText());
            consorcio.setTelefonoConsejo(telefonoConsejoTxt.getText());
            consorcio.setTelefonoEncargado(telefonoEncargadoTxt.getText());
            consorcio.setTelefonoEncargado1(telefonoEncargado1Txt.getText());
            consorcio.setTelefonoPorteria(telefonoPorteriaTxt.getText());
            int rowI = comboI.getSelectedIndex();
            consorcio.setTipoInscripcion(tiposInscripcion.get(rowI - 1).getCodigo());
            try {
                new ConsorcioService().saveConsorcio(consorcio);
                JOptionPane.showMessageDialog(this, "CONSORCIO GUARDADO CORRECTAMENTE");
            } catch (Exception ex) {
                Logger.getLogger(NuevoConsorcioFrame.class.getName()).log(Level.SEVERE, null, ex);
                JOptionPane.showMessageDialog(this, "ERROR Nro. 926 GUARDANDO CONSORCIO");
                return;
            }
            volver();
        }
    }

    private boolean validar() {
        codigo = 0;
        int o = 0;
        try {
            codigo = new ConsorcioService().getCodigoSiguiente();
            if (codigo != null) {
                o = 1;
            } else {
                o = 0;
            }
        } catch (Exception ex) {
            Logger.getLogger(NuevoConsorcioFrame.class.getName()).log(Level.SEVERE, null, ex);
            o = 0;
        }
        if (o == 0) {
            codigo = 0;
        }
        codigo += 1;
        if (razonSocialTxt.getText().isEmpty()) {
            JOptionPane.showMessageDialog(this, "DEBE INGRESAR UNA RAZON SOCIAL\nPARA EL CONSORCIO");
            razonSocialTxt.requestFocus();
            return false;
        }
        if (calleTxt.getText().isEmpty()) {
            JOptionPane.showMessageDialog(this, "DEBE INGRESAR UNA CALLE\nPARA EL DOMICILIO DEL CONSORCIO");
            calleTxt.requestFocus();
            return false;
        }
        if (numeroTxt.getText().isEmpty()) {
            JOptionPane.showMessageDialog(this, "DEBE INGRESAR UN NUMERO\nPARA EL DOMICILIO DEL CONSORCIO");
            numeroTxt.requestFocus();
            return false;
        }
        if (localidadTxt.getText().isEmpty()) {
            JOptionPane.showMessageDialog(this, "DEBE INGRESAR UNA LOCALIDAD\nPARA DOMICILIO DEL CONSORCIO");
            localidadTxt.requestFocus();
            return false;
        }
        if (provinciaTxt.getText().isEmpty()) {
            JOptionPane.showMessageDialog(this, "DEBE INGRESAR UNA PROVINCIA\nPARA EL DOMICILIO DEL CONSORCIO");
            provinciaTxt.requestFocus();
            return false;
        }
        int rowI = comboI.getSelectedIndex();
        if (rowI < 1) {
            JOptionPane.showMessageDialog(this, "SELECCIONE UN TIPO DE INSCRIPCION\nPARA EL CONSORCIO");
            comboI.requestFocus();
            return false;
        }
        int rowD = comboD.getSelectedIndex();
        if (rowD < 1) {
            JOptionPane.showMessageDialog(this, "DEBE SELECCIONAR UN TIPO DOCUMENTO (CUIT)\nPARA EL CONSORCIO");
            comboD.requestFocus();
            return false;
        }
        int rowA = comboA.getSelectedIndex();
        if (rowA < 1) {
            JOptionPane.showMessageDialog(this, "DEBE SELECCIONAR UNA ADMINISTRACION\nPARA EL CONSORCIO");
            comboA.requestFocus();
            return false;
        }
        return true;
    }

    private void llenarCombos() {
        comboI.removeAllItems();
        comboI.addItem("");
        comboD.removeAllItems();
        comboD.addItem("");
        comboA.removeAllItems();
        comboA.addItem("");
        administradores = null;
        try {
            administradores = new AdministradorService().getAllAdministradoresActivos();
        } catch (Exception ex) {
            Logger.getLogger(NuevoConsorcioFrame.class.getName()).log(Level.SEVERE, null, ex);
        }
        if (administradores != null && !administradores.isEmpty()) {
            for (Administrador a : administradores) {
                comboA.addItem(a.getRazonSocial());
            }
        } else {
            JOptionPane.showMessageDialog(this, "NO EXISTEN ADMINISTRADORES\nDEBE CREARLOS PRIMERO");
            volver();
        }
        for (TipoResponsable tr : TipoResponsable.values()) {
            comboI.addItem(tr.getDescripcion());
            tiposInscripcion.add(tr);
        }
        for (TipoDocumento td : TipoDocumento.values()) {
            comboD.addItem(td.getDocumento());
            tiposDocumento.add(td);
        }
    }
}
