/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ar.com.ventas.frame;

import ar.com.ventas.estructuras.Constantes;
import ar.com.ventas.main.MainFrame;

/**
 *
 * @author argia
 */
public class ReciboAbonos2Frame extends javax.swing.JFrame {

    /**
     * Creates new form ReciboAbonos2Frame
     */
    public ReciboAbonos2Frame() {
        initComponents();
        getContentPane().setBackground(new java.awt.Color(Constantes.getR(), Constantes.getG(), Constantes.getB()));
        this.setLocationRelativeTo(null);
//        setExtendedState(6); // this.MAXIMIZED_BOTH
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        reciboAbonosManualRb = new javax.swing.JRadioButton();
        reciboAbonoAutomaticoRb = new javax.swing.JRadioButton();
        renovarAbonosEnRecibosRb = new javax.swing.JRadioButton();
        volverBtn = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setTitle("SELECCIONE COMO GENERAR LOS RECIBOS");

        reciboAbonosManualRb.setText("RECIBO ABONOS MANUAL");
        reciboAbonosManualRb.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                reciboAbonosManualRbActionPerformed(evt);
            }
        });

        reciboAbonoAutomaticoRb.setText("RECIBO ABONO AUTOMATICO");
        reciboAbonoAutomaticoRb.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                reciboAbonoAutomaticoRbActionPerformed(evt);
            }
        });

        renovarAbonosEnRecibosRb.setText("RENOVAR RECIBOS ABONOS VENCIDOS");
        renovarAbonosEnRecibosRb.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                renovarAbonosEnRecibosRbActionPerformed(evt);
            }
        });

        volverBtn.setText("VOLVER");
        volverBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                volverBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(reciboAbonosManualRb)
                    .addComponent(reciboAbonoAutomaticoRb)
                    .addComponent(renovarAbonosEnRecibosRb))
                .addContainerGap(202, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(volverBtn)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addComponent(reciboAbonosManualRb)
                .addGap(18, 18, 18)
                .addComponent(reciboAbonoAutomaticoRb)
                .addGap(18, 18, 18)
                .addComponent(renovarAbonosEnRecibosRb)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 43, Short.MAX_VALUE)
                .addComponent(volverBtn)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void volverBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_volverBtnActionPerformed
        volver();
    }//GEN-LAST:event_volverBtnActionPerformed

    private void reciboAbonosManualRbActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_reciboAbonosManualRbActionPerformed
        reciboAbonosManual();
    }//GEN-LAST:event_reciboAbonosManualRbActionPerformed

    private void reciboAbonoAutomaticoRbActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_reciboAbonoAutomaticoRbActionPerformed
        reciboAbonosAutomatico();
    }//GEN-LAST:event_reciboAbonoAutomaticoRbActionPerformed

    private void renovarAbonosEnRecibosRbActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_renovarAbonosEnRecibosRbActionPerformed
        renovarAbonosRecibos();
    }//GEN-LAST:event_renovarAbonosEnRecibosRbActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ReciboAbonos2Frame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ReciboAbonos2Frame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ReciboAbonos2Frame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ReciboAbonos2Frame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ReciboAbonos2Frame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JRadioButton reciboAbonoAutomaticoRb;
    private javax.swing.JRadioButton reciboAbonosManualRb;
    private javax.swing.JRadioButton renovarAbonosEnRecibosRb;
    private javax.swing.JButton volverBtn;
    // End of variables declaration//GEN-END:variables

    private void volver() {
        MainFrame mf = new MainFrame();
        mf.setVisible(true);
        this.dispose();
    }

    private void reciboAbonosManual() {
        ReciboDeAbonosFrame rdaf = new ReciboDeAbonosFrame();
        rdaf.setVisible(true);
        this.dispose();
    }

    private void reciboAbonosAutomatico() {
        
    }

    private void renovarAbonosRecibos() {
        
    }
}
