/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ar.com.ventas.frame;

import ar.com.ventas.entities.Abono;
import ar.com.ventas.entities.Comprobante;
import ar.com.ventas.entities.Consorcio;
import ar.com.ventas.entities.Domicilio;
import ar.com.ventas.entities.Rubro;
import ar.com.ventas.entities.TitularCuit;
import ar.com.ventas.estructuras.Constantes;
import ar.com.ventas.main.MainFrame;
import ar.com.ventas.services.AbonoService;
import ar.com.ventas.services.ComprobanteService;
import ar.com.ventas.services.ConsorcioService;
import ar.com.ventas.services.TitularCuitService;
import ar.com.ventas.util.UtilFrame;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Mario
 */
public class ReconstruirAbonoFacturaFrame extends javax.swing.JFrame {

    private List<Abono> abonos;

    /**
     * Creates new form ReconstruirAbonoFacturaFrame
     */
    public ReconstruirAbonoFacturaFrame() {
        initComponents();
        getContentPane().setBackground(new java.awt.Color(Constantes.getR(), Constantes.getG(), Constantes.getB()));
//        this.setLocationRelativeTo(null);
        setExtendedState(6); // this.MAXIMIZED_BOTH

        llenar();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tabla = new javax.swing.JTable();
        volverBtn = new javax.swing.JButton();
        marcarComoInactivoBtn = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setTitle("VERIFICAR ABONO FACTURA");

        tabla.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "CONSORCIO", "ADMINISTRADOR", "ABONO", "RUBRO", "FACTURA", "NUMERO", "TITULAR"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                true, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tabla);

        volverBtn.setText("Volver");
        volverBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                volverBtnActionPerformed(evt);
            }
        });

        marcarComoInactivoBtn.setText("Marcar como Inactivo");
        marcarComoInactivoBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                marcarComoInactivoBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 678, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(marcarComoInactivoBtn)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(volverBtn)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 461, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(volverBtn)
                    .addComponent(marcarComoInactivoBtn))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void volverBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_volverBtnActionPerformed
        volver();
    }//GEN-LAST:event_volverBtnActionPerformed

    private void marcarComoInactivoBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_marcarComoInactivoBtnActionPerformed
        int row = tabla.getSelectedRow();
        if (row < 0) {
            JOptionPane.showMessageDialog(this, "SELECCIONE PARA DESACTIVAR");
            return;
        }
        marcarComoInactivo(row);
    }//GEN-LAST:event_marcarComoInactivoBtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ReconstruirAbonoFacturaFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ReconstruirAbonoFacturaFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ReconstruirAbonoFacturaFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ReconstruirAbonoFacturaFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ReconstruirAbonoFacturaFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton marcarComoInactivoBtn;
    private javax.swing.JTable tabla;
    private javax.swing.JButton volverBtn;
    // End of variables declaration//GEN-END:variables

    private void llenar() {
        UtilFrame.limpiarTabla(tabla);
        abonos = null;
        try {
            abonos = new AbonoService().getAllAbonosActivos();
        } catch (Exception ex) {
            Logger.getLogger(ReconstruirAbonoFacturaFrame.class.getName()).log(Level.SEVERE, null, ex);
        }
        DefaultTableModel tbl = (DefaultTableModel) tabla.getModel();
        for (Abono ab : abonos) {
            Integer codCons = ab.getConsorcio().getCodigo();
            Consorcio cons = null;
            try {
                cons = new ConsorcioService().getConsorcioByCodigo(codCons);
            } catch (Exception ex) {
                Logger.getLogger(ReconstruirAbonoFacturaFrame.class.getName()).log(Level.SEVERE, null, ex);
            }
            Domicilio dm = cons.getDomicilio();
            Rubro ru = ab.getRubro();
            String calle = dm.getCalle()
                    + dm.getNumero();
            Object o[] = new Object[7];
            o[0] = calle;
            o[1] = cons.getAdministrador().getNombreAdministrador();
            o[2] = ab.getId();
            o[3] = ru.getDetalle();

            Comprobante comp = null;
            try {
                comp = new ComprobanteService().getUltimoComprobanteByConsorcio(cons);
            } catch (Exception ex) {
                Logger.getLogger(ReconstruirAbonoFacturaFrame.class.getName()).log(Level.SEVERE, null, ex);
            }
            if (comp != null) {
                o[4] = comp.getId();
                o[5] = comp.getNumero();
                String cuit = comp.getCuitTitular();
                TitularCuit tc = null;
                try {
                    tc = new TitularCuitService().getTitularActivoByCuit(cuit);
                } catch (Exception ex) {
                    Logger.getLogger(ReconstruirAbonoFacturaFrame.class.getName()).log(Level.SEVERE, null, ex);
                }
                o[6] = tc.getPersona().getApellidoNombre();
            }
            tbl.addRow(o);
        }
        tabla.setModel(tbl);
    }

    private void volver() {
        MainFrame mf = new MainFrame();
        mf.setVisible(true);
        this.dispose();
    }

    private void marcarComoInactivo(int row) {
        Abono a = abonos.get(row);
        a.setActivo(false);
        int x = JOptionPane.showConfirmDialog(this, "CONFIRME ELIMINAR\n" + a.getRubro().getDetalle(), "Atención", JOptionPane.YES_NO_OPTION);
        if (x == 0) {
            try {
                new AbonoService().updateAbono(a);
            } catch (Exception ex) {
                Logger.getLogger(ReconstruirAbonoFacturaFrame.class.getName()).log(Level.SEVERE, null, ex);
            }
            llenar();
        }
    }
}
